<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Zeros and Ones – Intro Regression In R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Chapter7.html" rel="next">
<link href="./Chapter5.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0615981f0f11b1670b07f78b9ae6e573.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Chapter6.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Zeros and Ones</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Intro Regression In R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualize the Relationship</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Add a Line</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">How sure are you?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Assumptions Were Made</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Make it Work</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter6.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Zeros and Ones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Go Bigger</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Building and Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Well that’s weird</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#indicator-variables" id="toc-indicator-variables" class="nav-link active" data-scroll-target="#indicator-variables"><span class="header-section-number">6.1</span> Indicator variables</a></li>
  <li><a href="#indicator-only-regression-model" id="toc-indicator-only-regression-model" class="nav-link" data-scroll-target="#indicator-only-regression-model"><span class="header-section-number">6.2</span> Indicator only Regression Model</a></li>
  <li><a href="#adding-in-an-indicator" id="toc-adding-in-an-indicator" class="nav-link" data-scroll-target="#adding-in-an-indicator"><span class="header-section-number">6.3</span> Adding in an Indicator</a></li>
  <li><a href="#interacting-with-an-indicator" id="toc-interacting-with-an-indicator" class="nav-link" data-scroll-target="#interacting-with-an-indicator"><span class="header-section-number">6.4</span> Interacting with an Indicator</a>
  <ul class="collapse">
  <li><a href="#in-r" id="toc-in-r" class="nav-link" data-scroll-target="#in-r">In R</a></li>
  </ul></li>
  <li><a href="#sec-mlev_ind" id="toc-sec-mlev_ind" class="nav-link" data-scroll-target="#sec-mlev_ind"><span class="header-section-number">6.5</span> Multi-level factors in Regression</a></li>
  <li><a href="#on-your-own" id="toc-on-your-own" class="nav-link" data-scroll-target="#on-your-own">On Your Own</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Zeros and Ones</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="indicator-variables" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="indicator-variables"><span class="header-section-number">6.1</span> Indicator variables</h2>
<p>An indicator variable, also known as a dummy variable, is a variable used to represent membership in a specific category of a categorical variable. Using only the values 0 and 1, the indicator variable will indicate the presence of a particular attribute or membership in a category of interest with a 1, and use a 0 for everything else.</p>
<p>Indicator variables are essential when incorporating categorical variables—like treatment group, sex, or employment status—into linear regression models. For example, to represent whether each individual included in a survey is employed or unemployed, an indicator variable could be defined as 1 if the person is employed, and 0 if the person is unemployed.</p>
<p>For categorical variables with more than two categories, a separate indicator variable is created for each category except one, which becomes the reference (or baseline) group. This encoding, often called one-hot encoding, ensures that the model can estimate effects relative to the reference group while avoiding perfect collinearity (remember we need <span class="math inline">\(X^TX\)</span> to have an inverse). For instance, if we instead treated employment as having three categories of full-time, part-time, or unemployed we would create two indicator variables: one for full-time and one for part-time. Unemployed would then serve as the reference group.</p>
<p>The choice of which group serves as the reference group is arbitrary, but it will affect the interpretation of model coefficients. For this reason, if your categorical variable is ordinal, it is customary to select either the lowest or the highest ordered category as your reference group; Interpretation of coefficients relative to max or min just often makes the most sense.</p>
</section>
<section id="indicator-only-regression-model" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="indicator-only-regression-model"><span class="header-section-number">6.2</span> Indicator only Regression Model</h2>
<p>While not commonly done, you can create a simple linear regression model using only an indicator variable as a predictor. Consider again the <code>cats</code> data frame in the <code>MASS</code> library. This data contains not only the heart weight and body weight of 144 cats as we’ve seen in earlier models, but also the sex of those 144 cats. From <a href="#fig-catsex" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> below it is clear that the heart weight of female cats is a bit less on average than the heart weight of male cats.</p>
<div id="fig-catsex" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-catsex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-catsex" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-catsex-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-catsex-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter6_files/figure-html/fig-catsex-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-catsex" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-catsex-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Straight data
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-catsex" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-catsex-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-catsex-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter6_files/figure-html/fig-catsex-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-catsex" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-catsex-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Jittered sex for clarity
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catsex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Cat heart weight by sex, 1=Female
</figcaption>
</figure>
</div>
<p>If we fit a model of the form <span class="math inline">\(y=β_0+β_1x+ε\)</span> and have <span class="math inline">\(x=0\)</span> for female cats and <span class="math inline">\(x=1\)</span> for male cats what values of <span class="math inline">\(β_0\)</span> and <span class="math inline">\(β_1\)</span> should we expect? Since there are only two possible values of <span class="math inline">\(x\)</span>, there will be only two possible fitted values from our model: one corresponding to when <span class="math inline">\(x=0\)</span> and one for when <span class="math inline">\(x=1\)</span>. To minimize the sum of squared error, we want the output when <span class="math inline">\(x=0\)</span> to be equal to the mean heart weight for female cats and the output when <span class="math inline">\(x=1\)</span> to be equal to the mean heart weight for male cats. This is achieved when <span class="math inline">\(β_0\)</span> equals the mean heart weight for females and when <span class="math inline">\(β_0+β_1\)</span> mean heart rate for males. Therefore <span class="math inline">\(β_1\)</span> should be the difference between the two group means.</p>
<p>Here’s the work in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(cats<span class="sc">$</span>Hwt[cats<span class="sc">$</span>Sex<span class="sc">==</span><span class="st">"F"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.202128</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(cats<span class="sc">$</span>Hwt[cats<span class="sc">$</span>Sex<span class="sc">==</span><span class="st">"M"</span>])<span class="sc">-</span><span class="fu">mean</span>(cats<span class="sc">$</span>Hwt[cats<span class="sc">$</span>Sex<span class="sc">==</span><span class="st">"F"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.120553</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mod_cat_sex<span class="ot">&lt;-</span><span class="fu">lm</span>(Hwt<span class="sc">~</span>Sex, <span class="at">data=</span>cats)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_cat_sex)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) 9.202128  0.3250734 28.307842 2.959034e-60
SexM        2.120553  0.3960745  5.353924 3.379786e-07</code></pre>
</div>
</div>
<p>Just as suspected, the result gives us an intercept equal to the mean heart weight of female cats and a slope equal to the difference between male and female heart weights.</p>
</section>
<section id="adding-in-an-indicator" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="adding-in-an-indicator"><span class="header-section-number">6.3</span> Adding in an Indicator</h2>
<p>You can also add an indicator term to a model to create a linear equation of the form:</p>
<p><span class="math display">\[
y=β_0+β_1x_1+β_2x_2+ε
\]</span></p>
<p>Continuing with the cat heart weight example, we could fit this type of model with <span class="math inline">\(y=\)</span> heart weight, <span class="math inline">\(x_1=\)</span> body weight, and <span class="math inline">\(x_2=\)</span> sex (0=female, 1 = male)</p>
<p>The resulting model fit is:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate Std. Error    t value     Pr(&gt;|t|)
(Intercept) -0.41495263  0.7273243 -0.5705194 5.692336e-01
Bwt          4.07576892  0.2947885 13.8260785 5.119676e-28
SexM        -0.08209684  0.3040474 -0.2700133 7.875448e-01</code></pre>
</div>
</div>
<p>How can this be interpreted? First, note that the third row begins with <code>SexM</code> this is R’s way of communicating that for the Sex variable level M is the one that is corresponding to the indicator equalling 1. This tells us that the heart weight of cats is, on average, equal to -0.415 plus (4.0758 <span class="math inline">\(\times\)</span> body weight) for female cats, and (-0.415 plus -0.0821 ) plus (4.0758 <span class="math inline">\(\times\)</span> body weight) for male cats. Same slope for all cats, but intercepts that differ by -0.0821.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-catsexfit" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-catsexfit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter6_files/figure-html/fig-catsexfit-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" width="326">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catsexfit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Cat heart weight as function of body weight
</figcaption>
</figure>
</div>
</div>
</div>
<p>Hmmm… the two lines look pretty much the same. Why is that? Well take a look again at the model output above. We see that the difference in intercepts is only -0.0821, not a very big number. But scanning across this line in the output we also see that the p-value in the t-test of <span class="math inline">\(H_o:β_2=0\)</span> is 0.788 which means that with any reasonable <span class="math inline">\(\alpha\)</span> level, we would fail to reject the null. This means the coefficient associated with sex is not significantly different from zero, and the two lines aren’t really needed - one will do just fine.</p>
<p>Other times the indicator will matter quite a bit. Consider the <code>mtcars</code> dataframe from the <code>datasets</code> library. In a model predicting vehicle fuel efficiency as a function of horse power, does it help if we add in an indicator that is 1 for a manual transmission and 0 for an automatic? Our model will again be in the form of:<span class="math display">\[
y=β_0+β_1x_1+β_2x_2+ε
\]</span></p>
<p>with <span class="math inline">\(y=\)</span>mpg, <span class="math inline">\(x_1=\)</span>horsepower, and <span class="math inline">\(x_2=\)</span>manual transmission.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) 26.5849137 1.425094292 18.654845 1.073954e-17
hp          -0.0588878 0.007856745 -7.495191 2.920375e-08
am           5.2770853 1.079540576  4.888270 3.460318e-05</code></pre>
</div>
</div>
<p>In this case, the test of <span class="math inline">\(H_o:β_2=0\)</span> has a p-value that is 3^{-5} meaning there is strong evidence this additional term related to transmission type matters. In a plot of the fitted model we see:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mtcars_mpg_hp" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mtcars_mpg_hp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter6_files/figure-html/fig-mtcars_mpg_hp-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" width="364">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mtcars_mpg_hp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Car MPG as function of HP
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-mtcars_mpg_hp" class="quarto-xref">Figure&nbsp;<span>6.3</span></a> shows us very clearly that cars of equal horsepower tend to get better gas mileage if they are a manual transmission. The difference between the two lines is <span class="math inline">\(β_2\)</span>, 5.2771.</p>
</section>
<section id="interacting-with-an-indicator" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="interacting-with-an-indicator"><span class="header-section-number">6.4</span> Interacting with an Indicator</h2>
<p>Parallel lines are great and all, but there’s no reason to believe that the best model fit for two levels of your indicator should always have the same slope. Ideally we want a model that takes a form more like:<span class="math display">\[
y=β_0+β_1x_1+β_2x_2+β_3x_1x_2+ε
\]</span></p>
<p>With this structure, for our baseline level of <span class="math inline">\(x_2=0\)</span>, the <span class="math inline">\(β_2\)</span> and <span class="math inline">\(β_3\)</span> terms disappear since they are multiplied by zero, leaving you with the basic <span class="math inline">\(β_0\)</span> as intercept and <span class="math inline">\(β_1\)</span> as slope. When <span class="math inline">\(x_2=1\)</span> though, the <span class="math inline">\(β_2\)</span> and <span class="math inline">\(β_3\)</span> terms stick around and <span class="math inline">\(β_0+β_2\)</span> becomes the intercept and <span class="math inline">\(β_1+β_3\)</span> becomes the slope. Having a <span class="math inline">\(x_1x_2\)</span> term is called having an interaction between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>. The <span class="math inline">\(x_2\)</span> indicator value is interacting with the slope associated with your continuous <span class="math inline">\(x_1\)</span>.</p>
<p>Revisiting the cat heart and body weight data, might sex play a significant role in predicting heart weight if we allow slope to change as well as intercept? Here’s the R model summary for the revised model that includes the <span class="math inline">\(β_3x_1x_2\)</span> term:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)  2.981312  1.8428394  1.617782 0.1079604636
Bwt          2.636414  0.7759022  3.397869 0.0008845733
SexM        -4.165400  2.0617552 -2.020318 0.0452578391
Bwt:SexM     1.676265  0.8373255  2.001927 0.0472246471</code></pre>
</div>
</div>
<p>The last row labeled <code>Bwt:SexM</code> corresponds to our <span class="math inline">\(β_3x_1x_2\)</span> term. Reading across the output summary table shows us that this <span class="math inline">\(β_3\)</span> coefficient is estimated to be significantly different from 0 at the <span class="math inline">\(\alpha=0.05\)</span> level. The <span class="math inline">\(β_2\)</span> term allowing for different intercepts that was not significant in the limited <span class="math inline">\(y=β_0+β_1x_1+β_2x_2\)</span> model is now also showing a p-value below 0.05 at 0.0453. Plotted, the fits for male and female cats now look like the lines in <a href="#fig-cats_full" class="quarto-xref">Figure&nbsp;<span>6.4</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-cats_full" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cats_full-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter6_files/figure-html/fig-cats_full-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" width="336">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cats_full-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: Cat heart weight as function of body weight
</figcaption>
</figure>
</div>
</div>
</div>
<section id="in-r" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r">In R</h3>
<p>In the above example using <code>mtcars</code>, you may have noticed that the reference level wasn’t clear in the model summary output. That is because the transmission type variable, <code>am</code>, is pre-coded as a 0/1 indicator variable. The help menu for mtcars explains that am is a 0 for automatic, and 1 for manual. When read into R, it takes this 0/1 coding as a numeric 0/1 and doesn’t think of it as a factor type needing a reference level at all. Mathematically that is fine - it just makes interpretation a little trickier because you need to remember what is coded as 0 and what is coded as a 1.</p>
<p>Here is the code for the model described earlier predicting <code>mpg</code> as a function of <code>horsepower</code> and transmission type (<code>am</code>) :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># adding on +am to mpg~hp creates an additive beta for transmission</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>mod_mpg<span class="ot">&lt;-</span><span class="fu">lm</span>(mpg<span class="sc">~</span>hp<span class="sc">+</span>am, <span class="at">data=</span>mtcars)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_mpg)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) 26.5849137 1.425094292 18.654845 1.073954e-17
hp          -0.0588878 0.007856745 -7.495191 2.920375e-08
am           5.2770853 1.079540576  4.888270 3.460318e-05</code></pre>
</div>
</div>
<p>A simple run of <code>?mtcars</code> to pull up the help menu will show you that <code>am=0</code> for automatics and therefore automatic is the baseline reference level for transmission type and the <span class="math inline">\(β_2\)</span> shown for <code>am</code> is the change in intercept associated with a manual transmission.</p>
<p>In the <code>cats</code> data set explored this chapter, <code>Sex</code> is coded with F and M levels and is recognized by R as a factor type variable. You can include factors in your <code>lm</code> function input formula as-is and R will take care of the 0/1 coding behind the scenes for you. The first level of your factor will be treated as the 0 reference level. Here is code that first looks at the levels of <code>Sex</code>, then creates and summarizes the cat heart weight model including indicator interaction:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># look at levels to know which will be reference group</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(cats<span class="sc">$</span>Sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F" "M"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># multiplying the indicator factor creates both an additive beta for</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   different intercepts and the beta for the slope change</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>mod_cats_full<span class="ot">&lt;-</span><span class="fu">lm</span>(Hwt<span class="sc">~</span>Bwt<span class="sc">*</span>Sex, <span class="at">data=</span>cats)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_cats_full)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)  2.981312  1.8428394  1.617782 0.1079604636
Bwt          2.636414  0.7759022  3.397869 0.0008845733
SexM        -4.165400  2.0617552 -2.020318 0.0452578391
Bwt:SexM     1.676265  0.8373255  2.001927 0.0472246471</code></pre>
</div>
</div>
<p>As pointed out earlier, the row labels of <code>SexM</code> and <code>Bwt:SexM</code> also make clear level M is the one that is being treated as a 1, meaning level F must be our 0 reference group. If you want that switched, you can use <code>relevel</code> to change the ordering of the levels of the factor variable.</p>
</section>
</section>
<section id="sec-mlev_ind" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="sec-mlev_ind"><span class="header-section-number">6.5</span> Multi-level factors in Regression</h2>
<p>For categorical variables with more than two categories, we create a separate indicator variable for all categories except one, our baseline reference group. The below illustrates this process with an example from the <code>Cars93</code> data set from the <code>MASS</code> library. Vehicle type is a factor that takes on six different values: Compact, Large, Midsize, Small, Sporty, and Van. To incorporate this one factor with six levels, we create five new variables: Large, Midsize, Small, Sporty, and Van; each coded as a 0 or a 1. We do not need a variable for Compact - the Compact car level is signaled by not being any of the other types. This is often called one-hot encoding.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="onehot demo.jpg" class="img-fluid figure-img" alt="Six levels of car type coded to five indicators" width="388"></p>
<figcaption>One-hot encoding example</figcaption>
</figure>
</div>
<p>This is how car type can be included in a regression model - through the addition of five indicators. The order of the levels of car <code>Type</code> is, by default, alphabetical:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(Cars93<span class="sc">$</span>Type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Compact" "Large"   "Midsize" "Small"   "Sporty"  "Van"    </code></pre>
</div>
</div>
<p>To build a model of vehicle highway mpg as a function of weight, allowing for different intercepts for each type, the code looks much like what we’ve seen with the <code>lm</code> command before:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>mod_car93<span class="ot">&lt;-</span><span class="fu">lm</span>(MPG.highway<span class="sc">~</span>Weight<span class="sc">+</span>Type, <span class="at">data=</span>Cars93)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_car93)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate  Std. Error     t value     Pr(&gt;|t|)
(Intercept) 49.532032100 3.308855496 14.96953619 1.126489e-25
Weight      -0.006736186 0.001104706 -6.09772023 2.969242e-08
TypeLarge    2.088508950 1.450279960  1.44007296 1.534773e-01
TypeMidsize  0.098272245 1.115603939  0.08808883 9.300109e-01
TypeSmall    1.523993750 1.194802165  1.27551974 2.055600e-01
TypeSporty  -1.213784862 1.092190088 -1.11133115 2.695231e-01
TypeVan     -1.839809387 1.600556866 -1.14948080 2.535445e-01</code></pre>
</div>
</div>
<p>The main difference here is that withe the simple <code>+Type</code> we’ve now added five more β estimates; one for each of the new indicator terms. So the given intercept of 49.532 is the intercept for the baseline Compact car type, then we add 2.0885 to that to get the intercept for Large cars, add 0.0983 to 49.532 to get the intercept for Midsize cars, and so on through to adding -1.8398 to 49.532 for Vans.</p>
<p>Note in these results none of the p-values in the last column for these Type-related βs indicate the β is significantly different from 0. This does NOT mean that no two vehicle types have significantly different intercepts, it just means that none of the vehicle types have an intercept significantly different from Compact cars. If a different car type were selected to be the reference level, these β estimates and their corresponding p-values would change. Below are the results from the same model but using Van as the baseline reference rather than Compact.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>Type2<span class="ot">&lt;-</span><span class="fu">relevel</span>(Cars93<span class="sc">$</span>Type, <span class="st">"Van"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>mod_car93_Van<span class="ot">&lt;-</span><span class="fu">lm</span>(MPG.highway<span class="sc">~</span>Weight<span class="sc">+</span>Type2, <span class="at">data=</span>Cars93)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_car93_Van)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Estimate  Std. Error    t value     Pr(&gt;|t|)
(Intercept)  47.692222713 4.346958390 10.9714008 5.017827e-18
Weight       -0.006736186 0.001104706 -6.0977202 2.969242e-08
Type2Compact  1.839809387 1.600556866  1.1494808 2.535445e-01
Type2Large    3.928318337 1.349446429  2.9110591 4.586149e-03
Type2Midsize  1.938081632 1.272889330  1.5225846 1.315314e-01
Type2Small    3.363803137 2.055312537  1.6366383 1.053606e-01
Type2Sporty   0.626024525 1.637942803  0.3822017 7.032546e-01</code></pre>
</div>
</div>
<p>The resulting linear equations are exactly the same. Slope is obviously the same as before, and the intercepts are just expressed with relation to a different baseline. Intercept for Midsize cars for example was originally 49.532 + 0.0983=49.6303 and in the newer model the Midsize intercept is 47.6922 + 1.9381=49.6303. So no real change… just a different comparitor in the baseline position. You’ll also see that with Van as the baseline, the β associated with Large cars now has a p-value below 0.05 indicating it is significantly different from zero.</p>
<p>For the full model with interactions between car type and weight the addition of *Type leads to the addition of 10 new β estimates: five for unique intercepts plus five for unique slopes. And just as we saw with the additive indicator model, the values of the β estimates will change depending on what factor level is used as the baseline reference level.</p>
<p>With the default Compact as the reference level of type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mod_car93_full<span class="ot">&lt;-</span><span class="fu">lm</span>(MPG.highway<span class="sc">~</span>Weight<span class="sc">*</span>Type, <span class="at">data=</span>Cars93)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_car93_full)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Estimate   Std. Error    t value     Pr(&gt;|t|)
(Intercept)         4.781871e+01 10.199629443  4.6882791 1.099859e-05
Weight             -6.149055e-03  0.003486294 -1.7637797 8.153978e-02
TypeLarge          -7.310074e+00 16.890945386 -0.4327807 6.663243e-01
TypeMidsize        -2.810940e+00 12.244349583 -0.2295704 8.190043e-01
TypeSmall           1.774275e+01 11.678767728  1.5192314 1.325981e-01
TypeSporty         -3.170950e+00 11.741827087 -0.2700559 7.878041e-01
TypeVan            -1.878289e+01 27.646402307 -0.6793971 4.988232e-01
Weight:TypeLarge    2.419781e-03  0.005036981  0.4804029 6.322358e-01
Weight:TypeMidsize  7.724377e-04  0.004011302  0.1925653 8.477814e-01
Weight:TypeSmall   -6.858783e-03  0.004257682 -1.6109196 1.110875e-01
Weight:TypeSporty   6.787099e-04  0.004013261  0.1691168 8.661264e-01
Weight:TypeVan      4.283285e-03  0.007555762  0.5668898 5.723567e-01</code></pre>
</div>
</div>
<p>And with Van as the reference level of type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>mod_car93_full2<span class="ot">&lt;-</span><span class="fu">lm</span>(MPG.highway<span class="sc">~</span>Weight<span class="sc">*</span>Type2, <span class="at">data=</span>Cars93)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_car93_full2)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Estimate   Std. Error    t value  Pr(&gt;|t|)
(Intercept)         29.035823951 25.696130443  1.1299687 0.2618244
Weight              -0.001865770  0.006703380 -0.2783327 0.7814662
Type2Compact        18.782885727 27.646402307  0.6793971 0.4988232
Type2Large          11.472811300 29.009700360  0.3954819 0.6935270
Type2Midsize        15.971945860 26.574099715  0.6010343 0.5494954
Type2Small          36.525636382 26.318288216  1.3878424 0.1689910
Type2Sporty         15.611936118 26.346331477  0.5925658 0.5551224
Weight:Type2Compact -0.004283285  0.007555762 -0.5668898 0.5723567
Weight:Type2Large   -0.001863504  0.007625761 -0.2443696 0.8075625
Weight:Type2Midsize -0.003510847  0.006990822 -0.5022080 0.6168838
Weight:Type2Small   -0.011142068  0.007135048 -1.5615968 0.1222818
Weight:Type2Sporty  -0.003604575  0.006991947 -0.5155324 0.6075853</code></pre>
</div>
</div>
</section>
<section id="on-your-own" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="on-your-own">On Your Own</h2>
<ol type="1">
<li><p>Continuing with the examples above in <a href="#sec-mlev_ind" class="quarto-xref"><span>Section 6.5</span></a>:</p>
<ol type="a">
<li><p>What is the linear function to predict the highway fuel efficiency of a large car that weighs 3800 lbs using the model with Compact cars as the reference level?</p></li>
<li><p>Confirm the linear function from (a) still applies if you instead use the model fit with Vans as the reference level.</p></li>
<li><p>If the reference level is changed to Sporty, what do you expect the <code>TypeSmall</code> and <code>Weight:TypeSmall</code> coefficient estimates to be? Explain the reasoning and answer without running the new model.</p></li>
<li><p>Create a plot showing the six fit lines predicting highway mpg as a function of vehicle weight - one line per vehicle type. You’ll need the <code>Cars93</code> data set contained in the <code>MASS</code> library.</p></li>
<li><p>Are all assumptions necessary for inference met? Explain.</p></li>
</ol></li>
<li><p>Consider all cats with a body weight 3.5kg or less in the <code>cats</code> data frame from the MASS library.</p>
<ol type="a">
<li><p>Fit a simple linear regression model estimating a cat’s heart weight as a function of body weight. What is the equation of your fitted model?</p></li>
<li><p>Are all assumptions for inference met by your model in (a)? Explain.</p></li>
<li><p>Is there sufficient evidence that the slope is greater than 3? Explain.</p></li>
<li><p>Now fit a model estimating heart weight using body weight interacting with cat sex. What is the equation of the fitted model?</p></li>
<li><p>Are all assumptions for inference met by your model in (d)? Explain.</p></li>
<li><p>Is there sufficient evidence that the slope is greater than 3 for male cats? Is there evidence that the slope is less than 3 for female cats? Use an <span class="math inline">\(\alpha=0.05\)</span> level and explain your findings thoroughly.</p></li>
<li><p>Create a plot showing both the male and female cat fit lines. Jitter your body weights and use either plotting characters or color to distinguish which sex applies to each data point.</p></li>
<li><p>Why is it perfectly reasonable to calculate a prediction interval for the heart weight of a male cat weighing 3.3 kg, but not a good idea to make a prediction interval for a female cat weighing 3.3 kg?</p></li>
</ol></li>
<li><p>The crabs data set in the MASS library contains a variety of body measurements on two species of crabs.</p>
<ol type="a">
<li><p>Estimate a crab’s body depth as a function of carapace width, including crab species information in your model. What type of model makes the most sense: a model with an additive inclusion of a species indicator, or a model with a multiplicative interaction with a species indicator? Explain your answer.</p></li>
<li><p>What is the fitted equation of your selected model?</p></li>
<li><p>Do Orange crabs and Blue crabs have a significantly different intercept in a linear model using carapace width to explain body depth? Explain.</p></li>
<li><p>Are all assumptions for inference met in your model? Explain, using an <span class="math inline">\(\alpha=0.01\)</span> significance level in any tests you run. If your model needs fixing for inference procedures to be valid, fix it.</p></li>
<li><p>Using a model that meets all assumptions at the <span class="math inline">\(\alpha=0.01\)</span> level, fit and interpret a 90% confidence interval for the mean body depth of a Blue crab with a carapace width of 40mm. Then fit and interpret a 90% confidence interval for the mean body depth of an Orange crab with a carapace width of 40mm. How do they compare?</p></li>
<li><p>Now complete a model predicting body depth as a function of carapace width using an indicator term for crab sex. What indicator term is more helpful in predicting body depth: sex or species? Explain.</p></li>
</ol></li>
<li><p>The <code>openintro</code> library includes a data frame called fastfood that contains nutrition information for 515 fast food items.</p>
<ol type="a">
<li><p>Fit a model for food item calories as a function of total fat content. Include restaurant as an interaction term in your model. Which two restaurants have the most similar fit lines? What are those two fit lines?</p></li>
<li><p>Which restaurant has the steepest slope? Which has the least-steep slope? Are the two slopes significantly different from each other?</p></li>
<li><p>Fit a new model that does not include restaurant. Which restaurant from your first model comes closest to matching this restaurant-blind overall fit for calories as a function of fat? Explain.</p></li>
<li><p>Create a plot showing the raw data with three lines: the fit for the restaurant with the steepest slope, the fit for the restaurant with the least-steep slope, and the fit for the restaurant that most closely matched the restaurant neutral fit. Include a legend that provides the name of the restaurant associated with each model fit.</p></li>
</ol></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Chapter5.html" class="pagination-link" aria-label="Make it Work">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Make it Work</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Chapter7.html" class="pagination-link" aria-label="Go Bigger">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Go Bigger</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>