<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Add a Line – Intro Regression In R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Chapter3.html" rel="next">
<link href="./Chapter1.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0615981f0f11b1670b07f78b9ae6e573.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Chapter2.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Add a Line</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Intro Regression In R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualize the Relationship</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Add a Line</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">How sure are you?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Assumptions Were Made</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Make it Work</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Zeros and Ones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Go Bigger</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Building and Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Well that’s weird</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#describing-the-relationship-with-a-line" id="toc-describing-the-relationship-with-a-line" class="nav-link active" data-scroll-target="#describing-the-relationship-with-a-line"><span class="header-section-number">2.1</span> Describing the Relationship with a Line</a>
  <ul class="collapse">
  <li><a href="#Rcode" id="toc-Rcode" class="nav-link" data-scroll-target="#Rcode">In R</a></li>
  <li><a href="#Exercise" id="toc-Exercise" class="nav-link" data-scroll-target="#Exercise">On Your Own</a></li>
  </ul></li>
  <li><a href="#sec-resid" id="toc-sec-resid" class="nav-link" data-scroll-target="#sec-resid"><span class="header-section-number">2.2</span> Residuals</a></li>
  <li><a href="#sec-lsr" id="toc-sec-lsr" class="nav-link" data-scroll-target="#sec-lsr"><span class="header-section-number">2.3</span> Least-Squares Regression Line</a>
  <ul class="collapse">
  <li><a href="#in-r" id="toc-in-r" class="nav-link" data-scroll-target="#in-r">In R</a></li>
  <li><a href="#on-your-own" id="toc-on-your-own" class="nav-link" data-scroll-target="#on-your-own">On Your Own</a></li>
  </ul></li>
  <li><a href="#sstotal-ssregression-and-r2" id="toc-sstotal-ssregression-and-r2" class="nav-link" data-scroll-target="#sstotal-ssregression-and-r2"><span class="header-section-number">2.4</span> SSTotal, SSRegression, and <span class="math inline">\(R^2\)</span></a>
  <ul class="collapse">
  <li><a href="#in-r-1" id="toc-in-r-1" class="nav-link" data-scroll-target="#in-r-1">In R</a></li>
  <li><a href="#on-your-own-1" id="toc-on-your-own-1" class="nav-link" data-scroll-target="#on-your-own-1">On Your Own</a></li>
  </ul></li>
  <li><a href="#using-regression-models" id="toc-using-regression-models" class="nav-link" data-scroll-target="#using-regression-models"><span class="header-section-number">2.5</span> Using Regression Models</a>
  <ul class="collapse">
  <li><a href="#in-r-2" id="toc-in-r-2" class="nav-link" data-scroll-target="#in-r-2">In R</a></li>
  <li><a href="#on-your-own-2" id="toc-on-your-own-2" class="nav-link" data-scroll-target="#on-your-own-2">On Your Own</a></li>
  </ul></li>
  <li><a href="#matrix-notation" id="toc-matrix-notation" class="nav-link" data-scroll-target="#matrix-notation"><span class="header-section-number">2.6</span> Matrix Notation</a>
  <ul class="collapse">
  <li><a href="#in-r-3" id="toc-in-r-3" class="nav-link" data-scroll-target="#in-r-3">In R</a></li>
  <li><a href="#on-your-own-3" id="toc-on-your-own-3" class="nav-link" data-scroll-target="#on-your-own-3">On Your Own</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Add a Line</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="describing-the-relationship-with-a-line" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="describing-the-relationship-with-a-line"><span class="header-section-number">2.1</span> Describing the Relationship with a Line</h2>
<p>With a scatterplot in front of you and a linear trend evident the obvious next step is to draw a line on your plot. We begin with a simple method for fitting a line to a scatterplot that is easy to compute in four steps:</p>
<ol type="1">
<li><p>Calculate the median, 1st quartile, and 3rd quartile, of your X variable.</p></li>
<li><p>Calculate the median Y value of points with a corresponding X value less than the median you found in step 1.</p></li>
<li><p>Calculate the median Y value of points with a corresponding X value greater than the median you found in step 1.</p></li>
<li><p>Add the points corresponding to the 1st quartile of X paired with the median calculated in step 2 and the 3rd quartile of X paired with the median calculated in step 3 to your scatterplot. Draw a line connecting those two points.</p></li>
</ol>
<p>That’s it. You’re cutting the data in half from left to right along the X-axis, then finding the median X and Y on each side to create two points, then connecting the points with a line. What does that look like? <a href="#fig-mm" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> below walks through the process as applied to the <code>cars</code> speed and stopping distance data.</p>
<div id="fig-mm" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mm" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-mm-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mm-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter2_files/figure-html/fig-mm-1.png" class="img-fluid figure-img" data-ref-parent="fig-mm" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mm-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Find median X, divide
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mm" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-mm-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mm-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter2_files/figure-html/fig-mm-2.png" class="img-fluid figure-img" data-ref-parent="fig-mm" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mm-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Median X &amp; Y each side
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mm" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-mm-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mm-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter2_files/figure-html/fig-mm-3.png" class="img-fluid figure-img" data-ref-parent="fig-mm" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mm-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Connect two points
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Median-Median Line Steps
</figcaption>
</figure>
</div>
<p>First, the data is split into a left and right half based on the median vehicle speed, shown with the vertical grey dashed line. In the second plot, the <span class="math inline">\(25^{th}\)</span> and <span class="math inline">\(75^{th}\)</span> percentiles of speed are marked with green vertical lines and the median stopping distances for the two halves are marked with horizontal blue lines. Orchid dots mark the intersection of the medians. These two key dots are then joined with a line for the third graph on the right.</p>
<section id="Rcode" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="Rcode">In R</h3>
<p>A big part of the beauty of this method for drawing a line on a scatterplot is that it is simple. The ideas involved are nothing beyond quartiles and the algebra of connecting two points with a line. To find quartiles in R you’ll use the <code>quantile</code> function and base R arithmetic will get your through the rest of it.</p>
<p>Here’s the code to fit the line to the <code>cars</code> data frame shown in <a href="#fig-mm" class="quarto-xref">Figure&nbsp;<span>2.1</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make initial scatterplot to begin</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cars<span class="sc">$</span>speed, cars<span class="sc">$</span>dist, <span class="at">xlab=</span><span class="st">"Speed"</span>, <span class="at">ylab=</span><span class="st">"Stopping Distance"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># step 1: calculate the median, 1st quartile and 3rd quartile of X, weight</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>quartx<span class="ot">&lt;-</span><span class="fu">quantile</span>(cars<span class="sc">$</span>speed, <span class="fu">c</span>(.<span class="dv">5</span>, .<span class="dv">25</span>, .<span class="dv">75</span>))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># step 2: calculate the median Y of points to the left of the median X</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>med_y_left<span class="ot">&lt;-</span><span class="fu">median</span>(cars<span class="sc">$</span>dist[cars<span class="sc">$</span>speed<span class="sc">&lt;=</span>quartx[<span class="dv">1</span>]])</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># step 3: calculate the median Y of points to the right of the median X</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>med_y_right<span class="ot">&lt;-</span><span class="fu">median</span>(cars<span class="sc">$</span>dist[cars<span class="sc">$</span>speed<span class="sc">&gt;=</span>quartx[<span class="dv">1</span>]])</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># step 4: Add points and line connecting them</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(quartx[<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>], <span class="fu">c</span>(med_y_left, med_y_right), <span class="at">pch=</span><span class="dv">16</span>, <span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>slope<span class="ot">&lt;-</span>(med_y_right<span class="sc">-</span>med_y_left)<span class="sc">/</span>(quartx[<span class="dv">3</span>]<span class="sc">-</span>quartx[<span class="dv">2</span>])</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>intercept<span class="ot">&lt;-</span>med_y_left<span class="sc">-</span>(slope<span class="sc">*</span>quartx[<span class="dv">2</span>])</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(intercept, slope, <span class="at">col=</span><span class="st">"orchid3"</span>, <span class="at">lwd=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="Exercise" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="Exercise">On Your Own</h3>
<ol type="1">
<li>Create a scatterplot of vehicle weight and horsepower from the <code>mtcars</code> data frame.
<ol type="a">
<li><p>Overlay your plot with a median-median line in red.</p></li>
<li><p>Interpret the median-median line in context.</p></li>
</ol></li>
<li>Explore the variability in the median-median line approach through the following steps
<ol type="a">
<li>Write a function that takes in an X and a Y, then generates the slope and intercept for the median-median line.</li>
<li>Use your function on the <code>cars</code> data frame to identify the median-median line describing the relationship between vehicle speed and stopping distance.</li>
<li>Sample the rows of the <code>cars</code> data frame with replacement to create a new data frame with speed and stopping distance that is the same size as the original. Square brackets and <code>sample(1:nrows(cars), replace=TRUE)</code> will help you out with this. Once you have your new data frame, apply your median-median line function. How did the intercept and slope change?</li>
<li>Repeat the steps of part c 200 times in a loop, saving the new intercept and slope each time. Then generate histograms of your 200 intercepts and 200 slopes. How variable is the median-median line from one data sample to the next?</li>
</ol></li>
</ol>
</section>
</section>
<section id="sec-resid" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="sec-resid"><span class="header-section-number">2.2</span> Residuals</h2>
<p>Let’s consider a relatively small data set. The <code>bac</code> data from the <code>openintro</code> <span class="citation" data-cites="openintro">(<a href="#ref-openintro" role="doc-biblioref">Çetinkaya-Rundel et al. 2024</a>)</span> R library gives data from 16 student volunteers at Ohio State University who drank beer and then had their blood alcohol content measured.</p>
<p><a href="#fig-resid_lines" class="quarto-xref">Figure&nbsp;<span>2.2</span></a> shows the 16 data points from this study (one from each student) with the beer consumption level jittered for clarity. The red line is the result when using the Tukey median-median line method to describe the relationship between blood alcohol content (BAC) and beer consumption.</p>
<p>Obviously this red fit line does not exactly pass through every point. From the scatterplot it is clear that while BAC and beer consumption amounts are related, the relationship is not perfect and no straight line could perfectly pass through all 16 points. You’ll also see that each point has a thin line drawn vertically connecting it to the red line. The lengths of these lines are considered the error of the red line fit. These errors have a special name: <strong><em>residuals</em></strong>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-resid_lines" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resid_lines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter2_files/figure-html/fig-resid_lines-1.png" class="img-fluid figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-resid_lines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: Residual diagram
</figcaption>
</figure>
</div>
</div>
</div>
<p>A residual is the difference between the actual observed value of the dependent variable (<span class="math inline">\(y\)</span>) and the value predicted by the linear fit (<span class="math inline">\(\hat{y}\)</span><strong>)</strong>.</p>
<p>Mathematically, it is expressed as: <span class="math inline">\(Residual=y-\hat{y}\)</span> or specific to the <span class="math inline">\(i^{th}\)</span> observation, <span class="math inline">\(r_i=y_i-\hat{y}_i\)</span>, where <span class="math inline">\(y_i\)</span> is the observed value and <span class="math inline">\(\hat{y}_i\)</span> is the value predicted from the line.</p>
<p>Key points about residuals:</p>
<ul>
<li><p>A positive residual means the observed value is above the predicted value (the model underestimated).</p></li>
<li><p>A negative residual means the observed value is below the predicted value (the model overestimated).</p></li>
<li><p>The residuals represent the <u>vertical</u> distances between the data points and the regression line on a scatterplot. The errors are parallel to the y-axis, not projections meeting the linear fit at a right-angle.</p></li>
</ul>
</section>
<section id="sec-lsr" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-lsr"><span class="header-section-number">2.3</span> Least-Squares Regression Line</h2>
<p>With the idea of a residual established, we can move beyond the simple median-median line and define a new line of fit: the least-squares regression line. With this approach our fit line is defined as the line that minimizes the sum of the squared residuals.</p>
<p>Why the sum of <em>squared</em> residuals and not simply the sum of residuals? Recall that residuals can be both positive and negative. Errors from points above the line and errors from points below the line would cancel each other out in a simple sum of residuals.</p>
<p>Why not the sum of the absolute value of residuals? Well… calculus. Think back to your calculus classes. What was more straight-forward: finding the minimum of a smooth continuous polynomial function or finding the minimum of a function with a kink in it caused by an absolute value?</p>
<p>You can also see the squaring as a nice feature as it puts an added penalty whenever your line is far off. Big residuals squared become even bigger errors in the sum you’re minimizing.</p>
<p>Some notation for all this is needed now. Our goal is to model the relationship between a single independent variable <span class="math inline">\(x\)</span> and a dependent variable <span class="math inline">\(y\)</span> with a line in the form:</p>
<p><span class="math display">\[y=β_0+β_1x+ε\]</span></p>
<p>Where</p>
<ul>
<li><p><span class="math inline">\(y=\)</span> Dependent (response) variable</p></li>
<li><p><span class="math inline">\(x=\)</span> Independent (predictor) variable</p></li>
<li><p><span class="math inline">\(β_0=\)</span> Intercept (value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x=0\)</span>)</p></li>
<li><p><span class="math inline">\(β_1=\)</span> Slope (change in <span class="math inline">\(y\)</span> for a one-unit change in <span class="math inline">\(x\)</span>)</p></li>
<li><p><span class="math inline">\(ε=\)</span> Error term that captures deviations from the line (residuals)</p></li>
</ul>
<p>Minimizing the sum of squared errors means minimizing:</p>
<p><span class="math display">\[
\sum (y_i-(β_0+β_1x_i))^2
\]</span></p>
<p><span class="math display">\[
=\sum (y_i-β_0-β_1x_i)^2
\]</span></p>
<p>By differentiating with respect to <span class="math inline">\(β_0\)</span> and then separately differentiating with respect to <span class="math inline">\(β_1\)</span> , setting each to 0 and solving for the minimums you can find that the least-squares estimate for <span class="math inline">\(β_0\)</span> and <span class="math inline">\(β_1\)</span> are:</p>
<p><span class="math display">\[
β_1=\frac{\sum(x_i-\bar{x})(y_i-\bar{y})}{\sum(x_i-\bar{x})^2}
\]</span></p>
<p><span class="math display">\[β_0=\bar{y}-β_1\bar{x}\]</span></p>
<p>where <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(\bar{y}\)</span> are the sample means of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, respectively.</p>
<p><a href="#fig-med_ols" class="quarto-xref">Figure&nbsp;<span>2.3</span></a> shows the least-squares regression line added to the plot from <a href="#fig-resid_lines" class="quarto-xref">Figure&nbsp;<span>2.2</span></a>. The red line is the Median-Median fit of the data, the dashed blue line shows the least-squares regression fit.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-med_ols" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-med_ols-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter2_files/figure-html/fig-med_ols-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-med_ols-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.3: Median-Median and Least-Squares Lines
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now a question: If you swap your dependent and independent variables and fit a line to X~Y instead, will you get the same linear equation just solved for X instead of solved for Y? Nope. When BAC is fit as a function of beer consumption you get that <span class="math inline">\(BAC=-0.0127+0.0180\times beers\)</span>. If instead you fit beers as a function of BAC, then, <span class="math inline">\(beers=1.5288+44.5252\times BAC\)</span> which when solved for BAC comes to <span class="math inline">\(BAC=-0.0343-0.0225\times temperature\)</span>. Both of these are shown on <a href="#fig-swap_xy" class="quarto-xref">Figure&nbsp;<span>2.4</span></a> to show how different the results are:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-swap_xy" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-swap_xy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter2_files/figure-html/fig-swap_xy-1.png" id="fig-swap_xy" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-swap_xy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.4
</figcaption>
</figure>
</div>
</div>
</div>
<p>Why are they so different? It is all because of how residuals are defined. Remember our least-squares regression fit is designed to minimizes the sum of squared residuals and residuals are defined as the error measured parallel to the y-axis. When you change which term is y, you change the error measure that matters.</p>
<p>It is worth noting that every regression line will pass through the point <span class="math inline">\((\bar{x}, \bar{y})\)</span> and because of that, the point at which the two lines intersect is, and always will be, <span class="math inline">\((\bar{x}, \bar{y})\)</span>. With this data, that means <span class="math inline">\((4.812, 0.07375)\)</span>.</p>
<section id="in-r" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r">In R</h3>
<p>Least-squares linear regression is a foundational technique in statistics and data science. Some consider it the first step you’ll take into the world of machine learning. As such, it is built into base R and those formulas above are not ones you’ll need to memorize. R will do all the heavy lifting. Here’s the code to fit the blue regression line in <a href="#fig-med_ols" class="quarto-xref">Figure&nbsp;<span>2.3</span></a> above and pull out the slope and intercept.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>blue_model<span class="ot">&lt;-</span><span class="fu">lm</span>(bac<span class="sc">~</span>beers, <span class="at">data=</span>bac)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>blue_model<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)       beers 
-0.01270060  0.01796376 </code></pre>
</div>
</div>
<p>You can even draw the regression line on your scatterplot using the model object directly with the <code>abline</code> function. Here’s the code to create the plot and insert the line in the color blue with a line width of three:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bac<span class="sc">$</span>beers, bac<span class="sc">$</span>bac)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(blue_model, <span class="at">col=</span><span class="dv">4</span>, <span class="at">lwd=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="on-your-own" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="on-your-own">On Your Own</h3>
<ol type="1">
<li>Create a scatterplot of vehicle weight and horsepower from the <code>mtcars</code> data frame.
<ol type="a">
<li>Overlay your plot with a least-squares regression line in red.</li>
<li>What is the equation of your fitted line?</li>
</ol></li>
<li>Create a scatterplot of vehicle speed and stopping distance from the <code>cars</code> data frame.
<ol type="a">
<li>Overlay your plot with a least-squares regression line in the color of your choice.</li>
<li>What is the equation of your fitted line?</li>
</ol></li>
<li>Fit a least-squares model predicting a newborn’s father’s age as a function of the babies’ mother’s age using the <code>births14</code> data frame in the <code>openintro</code> library.
<ol type="a">
<li>What is the equation of your fitted line?</li>
<li>Make a scatterplot of the data with your fitted line superimposed on top.</li>
<li>Now fit the model predicting the mother’s age as a function of father’s age. What is the equation of the fitted line?</li>
<li>Adjust your new model by solving for father’s age and add the new model to your scatterplot.</li>
<li>Confirm the point of intersection is at <span class="math inline">\((\bar{x}, \bar{y})\)</span>.</li>
</ol></li>
<li>Explore the variability in the least-squares regression line approach through the following steps a. Identify the slope and intercept of the fitted regression line predicting car stopping distance as a function of speed from the <code>cars</code> data frame. (yes, this is the same as #2 above) b. Sample the rows of the <code>cars</code> data frame with replacement to create a new data frame with speed and stopping distance that is the same size as the original. Square brackets and <code>sample(1:nrows(cars), replace=TRUE)</code> will help you out with this. Once you have your new data frame, find the new least-squares slope and intercept. How did the line coefficients change? c.&nbsp;Repeat the steps of part b 200 times in a loop, saving the new intercept and slope each time. Then generate histograms of your 200 intercepts and 200 slopes. How variable is your regression line from one data sample to the next? d.&nbsp;Plot car speed and stopping distance in a scatterplot and overlay 10 of your fitted regression lines from part c.&nbsp;When you look at the 10 lines, how do they differ from eachother? Do they tend to be parallel? Is the variability in line placement the same across the range of x, or are there areas of x where the lines are more or less consistent?</li>
</ol>
</section>
</section>
<section id="sstotal-ssregression-and-r2" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="sstotal-ssregression-and-r2"><span class="header-section-number">2.4</span> SSTotal, SSRegression, and <span class="math inline">\(R^2\)</span></h2>
<p>In <a href="#sec-resid" class="quarto-xref"><span>Section 2.2</span></a> we discussed residuals as being the measure from each data point to the fitted line. There are two other important metrics in regression to be aware of.</p>
<p>Below in <a href="#fig-ssparts" class="quarto-xref">Figure&nbsp;<span>2.5</span></a> is the same student alcohol data with the blue least-squares line fit earlier. The horizontal grey dashed line is at 0.07375, the mean blood alcohol level across the 16 students.</p>
<div id="fig-ssparts" class="quarto-float quarto-figure quarto-figure-center anchored" alt="regression line diagram" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ssparts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="SST and friends beer.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="regression line diagram" width="408">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ssparts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.5: SST, SSE, and SSR
</figcaption>
</figure>
</div>
<p>The zoomed-in section of <a href="#fig-ssparts" class="quarto-xref">Figure&nbsp;<span>2.5</span></a> shows each of the three key components to be aware of in regression modeling drawn out for the point corresponding to our biggest drinker as an example.</p>
<ul>
<li><p>As you know from <a href="#sec-resid" class="quarto-xref"><span>Section 2.2</span></a>, the thin black line is the residual; the difference between the fitted regression model in blue, and the actual observed point. By design, our least-squares fit in blue minimizes the sum of the squared lengths of the black residual lines for all points. The sum of the squared errors is known as SSE, SSError, or SSResidual.</p></li>
<li><p>The green dot-dashed line is the distance from the observed point to the observed mean Y. The sum of these distances squared is known as Sum of Squares Total, SSTotal, or SST. This is a measure of the total variability of Y in your data set. The idea of the sum of squared distances to the mean as a measure of variability is not new: recall standard deviation from your intro stats course. By definition, the standard deviation of Y (a sample) is:<span class="math display">\[\sqrt{\frac{\sum(y-\bar{y})^2}{n-1}}\]</span></p>
<p>with the sum of squared distances to the mean right there in the numerator.</p></li>
<li><p>The third line shown dotted in orchid is the distance from the mean of Y to the regression line fit.</p>
<p>If beer consumption were unknown, our best guess for <span class="math inline">\(y_1\)</span> would be 0.07375, the overall average that corresponds to the horizontal grey line. However, using beer consumption and our fitted model, the best guess for <span class="math inline">\(y_1\)</span> is .14897, the fitted value corresponding to nine consumed beers calculated using the intercept and slope found earlier: <span class="math inline">\(-0.0127+(0.01796*9)=0.1489\)</span>.</p>
<p>The orchid dotted line shows this difference between the 0.1489 and 0.07375, and can be thought of as the value added by the linear model. It is graphically how much closer we are to the actual value of <span class="math inline">\(y_i\)</span> because we used the linear relationship to X in our estimation. The sum of squares of these differences attributed to the regression model is known as Sum Squares Regression, SSReg, or SSR.</p></li>
</ul>
<div style="page-break-after: always;"></div>
<p>In summary:</p>
<p><span class="math display">\[
SSError=SSE=\sum(y_i-\hat{y}_i)^2
\]</span></p>
<p><span class="math display">\[
SSTotal=SST=\sum(y_i-\bar{y})^2
\]</span></p>
<p><span class="math display">\[
SSRegression=SSR=\sum(\bar{y}_i-\hat{y}_i)^2
\]</span></p>
<p>Clearly from the visual in <a href="#fig-ssparts" class="quarto-xref">Figure&nbsp;<span>2.5</span></a> these three Sum of Squares measurements are closely related. In fact<span class="math display">\[
SSTotal=SSError+SSRegression
\]</span>Typically this relationship is relied on when calculating SSRegression as SSTotal and SSError are easier to calculate directly.</p>
<p>To avoid potential confusion, throughout this book SSR will refer only to SSRegression and SSE will be used for the Sum of Squared Residuals. Be aware though that some sources may use SSR to refer to SSRegression or SSResiduals.</p>
<p>All of this leads us to <span class="math inline">\(R^2\)</span>, the coefficient of determination. <span class="math display">\[R^2=1-\frac{SSError}{SSTotal}=\frac{SSReg}{SSTotal}\]</span></p>
<p>Put into words, this means <span class="math inline">\(R^2\)</span> is the proportion of variability in Y that has been explained by your linear regression model. Note that <span class="math inline">\(R^2\)</span> must always be positive and between 0 and 1, inclusive. The <span class="math inline">\(R^2\)</span> value also has nothing to do with the direction of the relationship between X and Y, only the strength of that relationship. The slope may be upward or downward sloping, <span class="math inline">\(R^2\)</span> only cares how closely the points follow the line.</p>
<div id="fig-rsquares" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rsquares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-rsquares" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-rsquares-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-rsquares-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter2_files/figure-html/fig-rsquares-1.png" class="img-fluid figure-img" data-ref-parent="fig-rsquares" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-rsquares-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) <span class="math inline">\(R^2=.99\)</span>
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-rsquares" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-rsquares-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-rsquares-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter2_files/figure-html/fig-rsquares-2.png" class="img-fluid figure-img" data-ref-parent="fig-rsquares" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-rsquares-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) <span class="math inline">\(R^2=.68\)</span>
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-rsquares" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-rsquares-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-rsquares-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter2_files/figure-html/fig-rsquares-3.png" class="img-fluid figure-img" data-ref-parent="fig-rsquares" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-rsquares-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) <span class="math inline">\(R^2=.22\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rsquares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.6: <span class="math inline">\(R^2\)</span>, Coefficient of Determination
</figcaption>
</figure>
</div>
<p>Consider the three plots in <a href="#fig-rsquares" class="quarto-xref">Figure&nbsp;<span>2.6</span></a>. On the left where the points closely follow the fitted red regression line, SSE is small, meaning SST and SSR are close to equal in value and <span class="math inline">\(R^2\)</span> is near 1 at 0.99. In the middle, the regression line does a fair job of describing the variability in Y so SSR is larger than SSE and the <span class="math inline">\(R^2\)</span> is 0.68. The downward slope of this middle graph is irrelevant. On the far right, the residuals are larger relative to the total variability of Y, so <span class="math inline">\(\frac{SSE}{SST}\)</span> is larger than in the other graphs making <span class="math inline">\(1-\frac{SSE}{SST}\)</span> smaller and <span class="math inline">\(R^2\)</span> is only 0.22.</p>
<p>What constitutes a “good” <span class="math inline">\(R^2\)</span> varies by discipline. If your data is related to engineering and is the X-Y relationship is related to a law of physics for instance, <span class="math inline">\(R^2\)</span> should be very nearly 1. If however you are working in the social sciences and the variability in the X-Y relationship is about people being different from each other, then an <span class="math inline">\(R^2\)</span> of 0.4 might be super exciting. Context matters when evaluating <span class="math inline">\(R^2\)</span>.</p>
<section id="in-r-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r-1">In R</h3>
<p>Code below calculates the SST and SSE from the least-squares line predicting BAC using beer consumption. SSR is calculated two ways; by subtracting SSE from SST, and directly using the mean of crawling age and model fitted values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>blue_model<span class="ot">&lt;-</span><span class="fu">lm</span>(bac<span class="sc">~</span>beers, <span class="at">data=</span>bac)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate mean BAC</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>mean_bac<span class="ot">&lt;-</span><span class="fu">mean</span>(bac<span class="sc">$</span>bac)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate fitted values for BAC</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>model_fit<span class="ot">&lt;-</span>blue_model<span class="sc">$</span>coef[<span class="dv">1</span>]<span class="sc">+</span>(blue_model<span class="sc">$</span>coef[<span class="dv">2</span>]<span class="sc">*</span>bac<span class="sc">$</span>beers)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># renaming just to make later calculations clear</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>bac_obs<span class="ot">&lt;-</span>bac<span class="sc">$</span>bac</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate SST</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>SSTotal<span class="ot">&lt;-</span><span class="fu">sum</span>((bac_obs<span class="sc">-</span>mean_bac)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>SSTotal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.029225</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate SSE</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>SSError<span class="ot">&lt;-</span><span class="fu">sum</span>((bac_obs<span class="sc">-</span>model_fit)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>SSError</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.005849655</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate SSR, two ways</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>SSReg<span class="ot">&lt;-</span>SSTotal<span class="sc">-</span>SSError</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>SSReg_long<span class="ot">&lt;-</span><span class="fu">sum</span>((model_fit<span class="sc">-</span>mean_bac)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(SSReg, SSReg_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02337535 0.02337535</code></pre>
</div>
</div>
<p>Note the two approaches to SSR produced the same result. There was an easier way though. Just as <code>$coef</code> after your model name will retreive the fitted model coeffiecents, there are similarly intuitive ways to quickly pull the fitted values and the residuals:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(blue_model<span class="sc">$</span>fitted.values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
0.005263 0.041191 0.077118 0.073750 0.099573 0.148973 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(blue_model<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
-0.027118 -0.017350  0.001773  0.000000  0.008623  0.041027 </code></pre>
</div>
</div>
<p>And here are three ways to calculate <span class="math inline">\(R^2\)</span>, the coefficient of determination.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>opt1<span class="ot">&lt;-</span><span class="dv">1</span><span class="sc">-</span>(SSError<span class="sc">/</span>SSTotal)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>opt2<span class="ot">&lt;-</span>SSReg<span class="sc">/</span>SSTotal</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>opt3<span class="ot">&lt;-</span><span class="fu">summary</span>(blue_model)<span class="sc">$</span>r.square</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(opt1, opt2, opt3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7998407 0.7998407 0.7998407</code></pre>
</div>
</div>
</section>
<section id="on-your-own-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="on-your-own-1">On Your Own</h3>
<ol type="1">
<li>Fit a least-squares model predicting vehicle hwy_mpg as a function of vehicle weight using the <code>cars04</code> data frame in the <code>openintro</code> library.
<ol type="a">
<li>What is the equation of your fitted line?</li>
<li>Make a scatterplot of the data with your fitted line superimposed on top.</li>
<li>Find SST, SSE, and SSR.</li>
<li>Find <span class="math inline">\(R^2\)</span>.</li>
</ol></li>
<li>Fit a least-squares model predicting total SAT score as a function of high school GPA using the <code>satgpa</code> data frame in the <code>openintro</code> library.
<ol type="a">
<li>What is the equation of your fitted line?</li>
<li>Make a scatterplot of the data with your fitted line superimposed on top.</li>
<li>Find SST, SSE, and SSR.</li>
<li>Find <span class="math inline">\(R^2\)</span>.</li>
</ol></li>
<li>Fit a least-squares model predicting a newborn’s father’s age as a function of the babies’ mother’s age using the <code>births14</code> data frame in the <code>openintro</code> library.
<ol type="a">
<li>What is the equation of your fitted line?</li>
<li>Make a scatterplot of the data with your fitted line superimposed on top.</li>
<li>Find SST, SSE, and SSR.</li>
<li>Find <span class="math inline">\(R^2\)</span>.</li>
</ol></li>
</ol>
</section>
</section>
<section id="using-regression-models" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="using-regression-models"><span class="header-section-number">2.5</span> Using Regression Models</h2>
<p>Great! We have a line! Now what? The two most common uses for a fitted regression line are:</p>
<ul>
<li><p>Using the slope as a descriptor of the relationship between X and Y</p></li>
<li><p>Using the fitted line to predict future observations</p></li>
</ul>
<p>Continuing our work with the student alcohol data, recall the fit: <span class="math display">\[bac=-0.0127+(0.01796\times beers)\]</span></p>
<p>The positive slope tells us that average BAC goes up as beer consumption goes up. Not surprising at all. Specifically, with a value of <span class="math inline">\(0.01796\)</span>, the model tells us the average BAC goes up by 0.01796 with every additional can of beer.</p>
<p>Using the full equation, we can also estimate that if someone drinks 4 beers, their blood alcohol level will likely be about 0.059 because <span class="math inline">\(-0.0127+(0.01796\times 4)=0.05914\)</span>. Similarly, a student who consumes seven beers likely has a BAC of about 0.113.</p>
<p>One important caveat for using your equation for estimation: extrapolation beyond the bounds of your observed data is not a good idea. What does that mean? Well think of a student with remarkably bad judgement who drinks 12 cans of beer. Our data doesn’t actually include any students drinking more than nine beers so by using our model to estimate the BAC at 12 beers we are making the assumption that the linear trend continues beyond the scope of our plot. Maybe it does and this student has a BAC just a bit over 0.2, but maybe it doesn’t and beers 10, 11, and 12 have a different impact than beers 1, 2, and 3, on increasing BAC. Estimations near the middle of our observed X range are where we feel the most confident; estimations beyond the range of observed X should be made with caution.</p>
<section id="in-r-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r-2">In R</h3>
<p>You already know that <code>model_name$coef</code> will get you your model coefficients. From there you can get predicted values using your line with a little algebra. There’s another way though; one that is particularly useful when you have more than one prediction to make. Here is how you can use the <code>predict.lm</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a data frame with the x-values you want a prediction for, making </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   sure the column name matches the x name used when you created your model</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>new_data<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">beers=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="fl">6.5</span>))</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># get your predicted values</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">predict.lm</span>(blue_model, new_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3 
0.02322692 0.04119068 0.10406385 </code></pre>
</div>
</div>
</section>
<section id="on-your-own-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="on-your-own-2">On Your Own</h3>
<ol type="1">
<li>Fit a least-squares model predicting vehicle hwy_mpg as a function of vehicle weight using the <code>cars04</code> data frame in the <code>openintro</code> library.
<ol type="a">
<li><p>What is the equation of your fitted line?</p></li>
<li><p>How do you expect hwy_mpg to change with a 100 lb increase in vehicle weight?</p></li>
<li><p>What highway gas mileage would you expect for a car that weighs 3,802 lbs?</p></li>
<li><p>What highway gas mileage would you expect for a car that weighs 1,700 lbs?</p></li>
<li><p>Which estimate, d or e, do you feel better about? Why?</p>
<div style="page-break-after: always;"></div></li>
</ol></li>
<li>Fit a least-squares model predicting total SAT score as a function of high school GPA using the <code>satgpa</code> data frame in the <code>openintro</code> library.
<ol type="a">
<li>What is the equation of your fitted line?</li>
<li>If Anne has a high school GPA of 3.3 and and Clark has a GPA of 3.8, how do you think Clark’s and Anne’s SAT scores compare? Explain with estimates of each SAT score using your model.</li>
</ol></li>
<li>Fit a least-squares model predicting a newborn’s father’s age as a function of the babies’ mother’s age using the <code>births14</code> data frame in the <code>openintro</code> library.
<ol type="a">
<li>What is the equation of your fitted line?</li>
<li>For each additional year of age for the mother, how much older do you anticipate the father to be?</li>
<li>Grace’s Mom was 29 when she was born, how old would you guess her father was?</li>
</ol></li>
</ol>
</section>
</section>
<section id="matrix-notation" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="matrix-notation"><span class="header-section-number">2.6</span> Matrix Notation</h2>
<p><a href="#sec-lsr" class="quarto-xref"><span>Section 2.3</span></a> expressed the form of our fitted model in the notation of a simple linear function (<span class="math inline">\(y=β_0+β_1x+ε\)</span>) but that isn’t the only option. Our model could also be expressed using matrix notation as:</p>
<p><span class="math display">\[
Y=Xβ+ε
\]</span></p>
<p>Where</p>
<ul>
<li><p><span class="math inline">\(Y\)</span> is an <span class="math inline">\(n\times 1\)</span> column matrix containing your <span class="math inline">\(n\)</span> observed outcomes</p></li>
<li><p><span class="math inline">\(X\)</span> is an <span class="math inline">\(n\times 2\)</span> matrix with the first column full of 1s to correspond to the intercept term of the linear model and the second column containing the <span class="math inline">\(x\)</span> values for your observed outcomes</p></li>
<li><p><span class="math inline">\(β\)</span> is <span class="math inline">\(2\times 1\)</span> containing <span class="math inline">\(β_0\)</span> and <span class="math inline">\(β_1\)</span> in separate rows</p></li>
<li><p><span class="math inline">\(ε\)</span> is an <span class="math inline">\(n\times 1\)</span> column matrix of the error terms</p></li>
</ul>
<p>So with the student alcohol data data:</p>
<p><span class="math display">\[
Y=\begin{bmatrix}
    0.1 \\
    0.03 \\
0.19\\
    \vdots \\
0.05\\
    \end{bmatrix}
and \space
X=\begin{bmatrix}
    1 &amp; 5 \\
    1 &amp; 2\\
1 &amp; 9 \\
    \vdots &amp; \vdots \\
    1 &amp; 4 \\
\end{bmatrix}
\]</span></p>
<p>To estimate <span class="math inline">\(β\)</span>, the <span class="math inline">\(\hatβ\)</span> is calculated by:</p>
<p><span class="math display">\[
\hatβ=(X^TX)^{-1}X^TY
\]</span></p>
<p>Which means your estimate for <span class="math inline">\(β\)</span> is dependent of <span class="math inline">\(X^TX\)</span> having an inverse. No inverse, no <span class="math inline">\(\hat{β}\)</span>.</p>
<p>Putting this <span class="math inline">\(\hatβ\)</span> back in our model equation, this means</p>
<p><span class="math display">\[\hat{Y}=X\hatβ\]</span> <span class="math display">\[\hat{Y}=X(X^TX)^{-1}X^TY\]</span></p>
<p>We then define <span class="math inline">\(X(X^TX)^{-1}X^T\)</span> as <span class="math inline">\(H\)</span>, the “hat matrix” because <span class="math inline">\(HY=\hat{Y}\)</span>. H “puts a hat” on Y. The hat matrix will play a role later on in chapter XXXXXXX.<br>
</p>
<section id="in-r-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r-3">In R</h3>
<p>You won’t do it regularly, but it’s not a bad exercise to work through fitting a linear model with matrix algebra rather than the <code>lm</code> shortcut offered by R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>Y_mat<span class="ot">&lt;-</span><span class="fu">matrix</span>(bac<span class="sc">$</span>bac, <span class="at">ncol=</span><span class="dv">1</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>X_mat<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">16</span>), bac<span class="sc">$</span>beers), <span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>XTX<span class="ot">&lt;-</span><span class="fu">t</span>(X_mat)<span class="sc">%*%</span>X_mat</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>XTX_inv<span class="ot">&lt;-</span><span class="fu">solve</span>(XTX)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>XTX_invXT<span class="ot">&lt;-</span>XTX_inv<span class="sc">%*%</span><span class="fu">t</span>(X_mat)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>beta_hat<span class="ot">&lt;-</span>XTX_invXT<span class="sc">%*%</span>Y_mat</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>beta_hat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            [,1]
[1,] -0.01270060
[2,]  0.01796376</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>lm_mod<span class="ot">&lt;-</span><span class="fu">lm</span>(bac<span class="sc">~</span>beers, <span class="at">data=</span>bac)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>lm_mod<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)       beers 
-0.01270060  0.01796376 </code></pre>
</div>
</div>
<p>Yay! They match, just as expected.</p>
</section>
<section id="on-your-own-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="on-your-own-3">On Your Own</h3>
<ol type="1">
<li>Fit a least-squares model predicting total SAT score as a function of high school GPA using the <code>satgpa</code> data frame in the <code>openintro</code> library.
<ol type="a">
<li>What is the <span class="math inline">\((X^TX)^{-1}\)</span> matrix in the interim calculation of <span class="math inline">\(\hatβ\)</span>?</li>
<li>Confirm the model fit using <code>lm</code> matches the fit using matrix algebra.</li>
<li>What is the value in the 1,1 position of the hat matrix?</li>
</ol></li>
<li>No data now, just linear algebra:
<ol type="a">
<li>What are the dimensions of the hat matrix?</li>
<li>What does <span class="math inline">\(HH\)</span> equal?</li>
</ol></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-openintro" class="csl-entry" role="listitem">
Çetinkaya-Rundel, Mine, David Diez, Andrew Bray, Albert Y. Kim, Ben Baumer, Chester Ismay, Nick Paterno, and Christopher Barr. 2024. <span>“Openintro: Datasets and Supplemental Functions from ’OpenIntro’ Textbooks and Labs.”</span> <a href="https://doi.org/10.32614/CRAN.package.openintro">https://doi.org/10.32614/CRAN.package.openintro</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Chapter1.html" class="pagination-link" aria-label="Visualize the Relationship">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualize the Relationship</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Chapter3.html" class="pagination-link" aria-label="How sure are you?">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">How sure are you?</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>