<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Building and Selection – Intro Regression In R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Chapter9.html" rel="next">
<link href="./Chapter7.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0615981f0f11b1670b07f78b9ae6e573.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Chapter8.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Building and Selection</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Intro Regression In R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualize the Relationship</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Add a Line</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">How sure are you?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Assumptions Were Made</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Make it Work</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Zeros and Ones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Go Bigger</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter8.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Building and Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Well that’s weird</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#measures-of-model-strength" id="toc-measures-of-model-strength" class="nav-link active" data-scroll-target="#measures-of-model-strength"><span class="header-section-number">8.1</span> Measures of model strength</a>
  <ul class="collapse">
  <li><a href="#test-set-and-training-set" id="toc-test-set-and-training-set" class="nav-link" data-scroll-target="#test-set-and-training-set"><span class="header-section-number">8.1.1</span> Test Set and Training Set</a></li>
  <li><a href="#in-r" id="toc-in-r" class="nav-link" data-scroll-target="#in-r">In R</a></li>
  <li><a href="#k-fold-cross-validation" id="toc-k-fold-cross-validation" class="nav-link" data-scroll-target="#k-fold-cross-validation"><span class="header-section-number">8.1.2</span> K-fold cross-validation</a></li>
  <li><a href="#in-r-1" id="toc-in-r-1" class="nav-link" data-scroll-target="#in-r-1">In R</a></li>
  <li><a href="#adjusted-r2" id="toc-adjusted-r2" class="nav-link" data-scroll-target="#adjusted-r2"><span class="header-section-number">8.1.3</span> Adjusted <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#aic-and-bic" id="toc-aic-and-bic" class="nav-link" data-scroll-target="#aic-and-bic"><span class="header-section-number">8.1.4</span> AIC and BIC</a></li>
  </ul></li>
  <li><a href="#model-building" id="toc-model-building" class="nav-link" data-scroll-target="#model-building"><span class="header-section-number">8.2</span> Model Building</a>
  <ul class="collapse">
  <li><a href="#forward-selection" id="toc-forward-selection" class="nav-link" data-scroll-target="#forward-selection"><span class="header-section-number">8.2.1</span> Forward Selection</a></li>
  <li><a href="#backward-elimination" id="toc-backward-elimination" class="nav-link" data-scroll-target="#backward-elimination"><span class="header-section-number">8.2.2</span> Backward Elimination</a></li>
  <li><a href="#step-wise" id="toc-step-wise" class="nav-link" data-scroll-target="#step-wise"><span class="header-section-number">8.2.3</span> Step-wise</a></li>
  </ul></li>
  <li><a href="#building-examples-in-r" id="toc-building-examples-in-r" class="nav-link" data-scroll-target="#building-examples-in-r"><span class="header-section-number">8.3</span> Building Examples in R</a>
  <ul class="collapse">
  <li><a href="#forward" id="toc-forward" class="nav-link" data-scroll-target="#forward"><span class="header-section-number">8.3.1</span> Forward</a></li>
  <li><a href="#backward" id="toc-backward" class="nav-link" data-scroll-target="#backward"><span class="header-section-number">8.3.2</span> Backward</a></li>
  <li><a href="#step-wise-1" id="toc-step-wise-1" class="nav-link" data-scroll-target="#step-wise-1"><span class="header-section-number">8.3.3</span> Step-wise</a></li>
  </ul></li>
  <li><a href="#best-model-of-size-p" id="toc-best-model-of-size-p" class="nav-link" data-scroll-target="#best-model-of-size-p"><span class="header-section-number">8.4</span> Best model of size p</a></li>
  <li><a href="#lasso-regression" id="toc-lasso-regression" class="nav-link" data-scroll-target="#lasso-regression"><span class="header-section-number">8.5</span> Lasso Regression</a>
  <ul class="collapse">
  <li><a href="#in-r-2" id="toc-in-r-2" class="nav-link" data-scroll-target="#in-r-2">In R</a></li>
  </ul></li>
  <li><a href="#principal-components-analysis-pca" id="toc-principal-components-analysis-pca" class="nav-link" data-scroll-target="#principal-components-analysis-pca"><span class="header-section-number">8.6</span> Principal Components Analysis (PCA)</a>
  <ul class="collapse">
  <li><a href="#in-r-3" id="toc-in-r-3" class="nav-link" data-scroll-target="#in-r-3">In R</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Building and Selection</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="measures-of-model-strength" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="measures-of-model-strength"><span class="header-section-number">8.1</span> Measures of model strength</h2>
<section id="test-set-and-training-set" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="test-set-and-training-set"><span class="header-section-number">8.1.1</span> Test Set and Training Set</h3>
<p>It may seem counter-intuitive but sometimes the best choice you can make is to NOT use all of your data when fitting your model. If you begin by splitting your data into two, you can fit the model on one set, known as the “training set”, and then test how well the model performs on the remaining “test set”. This helps protect you from creating a model that is so well tuned to your specific data that it isn’t generalizable to the full population and won’t produce helpful predictions.</p>
<p>Discretion is allowed when deciding the relative sizes of the training and testing sets. At most you would split the data 50/50 putting half in each set randomly. In some cases with limited data you might shift that to putting as much as 80% in the training set and holding out the remaining 20% for a sanity check.</p>
</section>
<section id="in-r" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r">In R</h3>
<p>Below is an example using the reduced glass refraction index data just seen at the end of <a href="Chapter7.html#sec-multico" class="quarto-xref"><span>Section 7.6</span></a>. The fgl glass data frame has 214 rows to start with.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set seed for reproducability</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># randomly select 150 rows for the training set</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>train_index<span class="ot">&lt;-</span><span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">214</span>, <span class="dv">150</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># put row numbers not selected into the test set</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>test_index<span class="ot">&lt;-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">214</span>)[<span class="sc">!</span><span class="fu">is.element</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">214</span>, train_index)]</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># create the two data sets</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>glass_train<span class="ot">&lt;-</span>fgl[train_index,]</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>glass_test<span class="ot">&lt;-</span>fgl[test_index,]</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the model with the training set</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>glass_model<span class="ot">&lt;-</span><span class="fu">lm</span>(RI<span class="sc">~</span>Al<span class="sc">+</span>Si<span class="sc">+</span>Ca<span class="sc">+</span>Ba, <span class="at">data=</span>glass_train)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># find mean squared error in training set</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(glass_model<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.160116</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find mean squared error in test set</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>fit_values<span class="ot">&lt;-</span><span class="fu">predict</span>(glass_model, glass_test)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>test_errors<span class="ot">&lt;-</span>fit_values<span class="sc">-</span>glass_test<span class="sc">$</span>RI</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(test_errors<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9209567</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># if you want a formal test, can do t-test of errors</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(glass_model<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>, test_errors<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  glass_model$residuals^2 and test_errors^2
t = 0.58113, df = 152.37, p-value = 0.562
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.5738999  1.0522177
sample estimates:
mean of x mean of y 
1.1601156 0.9209567 </code></pre>
</div>
</div>
<p>This shows that there is no evidence our model fitted using the training data doesn’t perform just as well on our test data. With this we can be confident that future refraction index values predicted using the model are reasonably accurate.</p>
</section>
<section id="k-fold-cross-validation" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="k-fold-cross-validation"><span class="header-section-number">8.1.2</span> K-fold cross-validation</h3>
<p>What if we just got lucky with our test set and training set sampling? K-fold cross-validation takes the idea of test/training set validation to the next level. Instead of separating the data into just two parts, a test set and a training set, k-fold cross validation splits the data into k parts. Often k is set to 5 or 10, but there’s no reason you can’t select any other number provided you have enough rows to reasonably split.</p>
<p>Once the data is split, the model is then fit k times; each time using k-1 groups as the training set and the held out group as the test set. <a href="#fig-kfold" class="quarto-xref">Figure&nbsp;<span>8.1</span></a> below illustrates what would happen with 4-fold cross validation on a data set with only 8 rows.</p>
<p>First the 8 rows are randomly grouped into four groups of 2. The model is then run 4 times. In the example, rows 1 and 7 are in fold 1. The first time the model is fit, fold 1 points are set aside for testing and the model is trained on rows 2,3,4,5,6, and 8. For model 2, our second fold containing rows 2 and 3 are set aside for testing, and the model is trained using rows 1,4,5,6,7, and 8. In the end you’re left with four examples of how well the model fit using the approach you’ve selected fits data that was not involved in the fitting.</p>
<div id="fig-kfold" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kfold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kfold_table.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kfold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: Four-fold cross validation diagram
</figcaption>
</figure>
</div>
</section>
<section id="in-r-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r-1">In R</h3>
<p>Continuing with the glass refractive index scenario, we’ll complete 10-fold cross validation of a model containing Al, Si, Ca, and Ba as linear predictors using the <code>train</code> function in the <code>caret</code> library.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set seed for reproducability</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the parameters. Method is cross validation, k=10.</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>train_params <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Train your k models.  Specify lm is type of model,</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co">#     and put in the training parameters set above</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>glass_models <span class="ot">&lt;-</span> <span class="fu">train</span>(RI <span class="sc">~</span> Al<span class="sc">+</span>Si<span class="sc">+</span>Ca<span class="sc">+</span>Ba, <span class="at">data=</span>fgl,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"lm"</span>,<span class="at">trControl =</span> train_params)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># View the results of the cross-validation</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>glass_models<span class="sc">$</span>resample</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        RMSE  Rsquared       MAE Resample
1  0.4672234 0.9570430 0.3934590   Fold01
2  0.6537417 0.9465408 0.5239035   Fold02
3  1.0238911 0.8434257 0.6182354   Fold03
4  1.4876875 0.7103225 1.0625717   Fold04
5  1.1690601 0.8168152 0.9380207   Fold05
6  1.0556602 0.8918505 0.8826193   Fold06
7  0.5904965 0.9885397 0.4773744   Fold07
8  1.2919068 0.7462664 0.7501642   Fold08
9  1.3814389 0.7731487 0.8307277   Fold09
10 1.0430018 0.8797080 0.7720872   Fold10</code></pre>
</div>
</div>
<p>These results indicate that over the 10 folds, the worst RMSE (square-root of mean squared error) among test holdouts happened when Fold4 was withheld from training. In this worst-case, the RMSE was 1.487. In the best-case, when Fold 1 was withheld, the RMSE was only 0.467. These are RMSEs calculated on the fold that was used as testing, not the folds that were used in training. If you prefer, the <span class="math inline">\(R^2\)</span> values for the testing holdouts, and the MAE (mean absolute error) for the testing holdouts are also given for each of the k folds. Some variability over the folds is to be expected, and these ten look reasonably consistent indicating the <code>RI~Al+Si+Ba+Ca</code> model approach is not over-fitting and should apply generally to the population.</p>
</section>
<section id="adjusted-r2" class="level3" data-number="8.1.3">
<h3 data-number="8.1.3" class="anchored" data-anchor-id="adjusted-r2"><span class="header-section-number">8.1.3</span> Adjusted <span class="math inline">\(R^2\)</span></h3>
<p>Back in Chapter 2 we defined <span class="math inline">\(R^2\)</span>, the coefficient of determination, as:</p>
<p><span class="math display">\[R^2=1-\frac{SSError}{SSTotal}=\frac{SSReg}{SSTotal}\]</span></p>
<p>So whenever the sum of squared residuals, <span class="math inline">\(SSError\)</span>, decreases, the <span class="math inline">\(R^2\)</span> goes up. In the world of multiple regression this creates a bit of a problem because every time you add a new term to the regression model the sum of squared residuals will go down whether the new term is really helpful or not. That’s why judging two models against each other using <span class="math inline">\(R^2\)</span> just won’t work. Enter adjusted <span class="math inline">\(R^2\)</span>.</p>
<p><span class="math display">\[R_{adj}^2=1-\frac{SSError/(n-p-1)}{SSTotal/(n-1)}\]</span></p>
<p>Where <span class="math inline">\(n\)</span> is the number of observations and <span class="math inline">\(p\)</span> is the number of predictor variables. This makes it so just adding terms won’t necessarily increase your <span class="math inline">\(R^2\)</span> - it will only improve if the increase in <span class="math inline">\(p\)</span> is adding real value to your model.</p>
<p>Getting this adjusted <span class="math inline">\(R^2\)</span> from R is simple. The basic model summary output includes this adjusted <span class="math inline">\(R^2\)</span> right after the <span class="math inline">\(R^2\)</span> value you’ve already come to know and love. Below is a highlighted example from the reduced glass refraction index model. The basic <span class="math inline">\(R^2\)</span> with no adjustment is given as 0.8914, and the <span class="math inline">\(R_{adj}^2\)</span> is given as 0.8883. Since the two are close in value, that is an indication that every term in the linear model is providing additional insight into the value of refraction index.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="adjR_example.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</section>
<section id="aic-and-bic" class="level3" data-number="8.1.4">
<h3 data-number="8.1.4" class="anchored" data-anchor-id="aic-and-bic"><span class="header-section-number">8.1.4</span> AIC and BIC</h3>
<p>AIC (Akaike’s Information Criterion) and BIC (Bayes Information Criterion) are two metrics used to compare the relative strength of competing models. The specific values of AIC and BIC have no real meaning, but the relative size of AIC and BIC of two or more possible models can help you decide which model to use.</p>
<p>Calculation of both AIC and BIC includes the log of the likelihood of the model under review. What is a model’s likelihood? Simply put: it’s the probability of seeing the observed data if the fitted model is the truth. The process to figuring out this likelihood is beyond our scope so we’ll rely on R to do the work for us, but it’s good to have a sense of what it’s measuring.</p>
<p><span class="math display">\[
AIC=2(p+2)-2ln(\hat L)
\]</span></p>
<p>and</p>
<p><span class="math display">\[
BIC=ln(n)(p+2)-2ln(\hat L)
\]</span></p>
<p>where <span class="math inline">\(\hat L\)</span> is the likelihood, <span class="math inline">\(p\)</span> is the number of independent predictors in your model, and <span class="math inline">\(n\)</span> is the number of observations. Notice the two are quite similar; the only difference is AIC has the number of estimated parameters multiplied by 2, while BIC penalizes larger parameter counts by a factor of <span class="math inline">\(ln(n)\)</span>.</p>
<p>For both AIC and BIC, the model with the lower value is the better choice. The <code>stats</code> library in R (a library usually installed by default) contains both an <code>AIC</code> and a <code>BIC</code> function for calculating these measures.</p>
<p>Here is an example considering two different models for glass refraction index; one with glass type indicators and one without:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>mod_glass2<span class="ot">&lt;-</span><span class="fu">lm</span>(RI<span class="sc">~</span>Na<span class="sc">+</span>Al<span class="sc">+</span>Si<span class="sc">+</span>K<span class="sc">+</span>Ca<span class="sc">+</span>Ba<span class="sc">+</span>Fe<span class="sc">+</span>vehicle<span class="sc">+</span>headlight, <span class="at">data=</span>fgl)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>mod_glass3<span class="ot">&lt;-</span><span class="fu">lm</span>(RI<span class="sc">~</span>Na<span class="sc">+</span>Al<span class="sc">+</span>Si<span class="sc">+</span>K<span class="sc">+</span>Ca<span class="sc">+</span>Ba<span class="sc">+</span>Fe, <span class="at">data=</span>fgl)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_glass2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 598.3572</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_glass3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 625.5007</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(mod_glass2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 635.383</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(mod_glass3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 655.7945</code></pre>
</div>
</div>
<p>In this case AIC and BIC agree that the model including glass type is better than the model without type. It is not always the case that AIC and BIC will agree though. That’s why for scientific rigor you should select which measure you want to use prior to calculating them.</p>
</section>
</section>
<section id="model-building" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="model-building"><span class="header-section-number">8.2</span> Model Building</h2>
<p>With <span class="math inline">\(R_{adj}^2\)</span>, AIC, and BIC we now have three different approaches to measure the quality of a model. This opens the door to ways we can build a multiple regression model piece by piece.</p>
<section id="forward-selection" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="forward-selection"><span class="header-section-number">8.2.1</span> Forward Selection</h3>
<p>The forward selection process is exactly what is sounds like: adding one variable at a time. At each step of this approach, each potential predictor is considered and one that improves <span class="math inline">\(R_{adj}\)</span> the most, or decreases AIC or BIC the most, is added to the model. The process continues until adding one more term does not improve your performance metric.</p>
</section>
<section id="backward-elimination" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="backward-elimination"><span class="header-section-number">8.2.2</span> Backward Elimination</h3>
<p>This approach to model building is also exactly what it sounds like. With backward selection you begin with a large model including all possible predictors and then remove them one by one. Which one should be removed at each step can be decided based on which has the highest p-value for the test on <span class="math inline">\(\hat\beta\)</span>, by which one, when removed, increases <span class="math inline">\(R_{adj}\)</span> the most, or by which one, when removed, decreases AIC or BIC the most. The process stops when removing any additional terms will only hurt the model quality.</p>
</section>
<section id="step-wise" class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="step-wise"><span class="header-section-number">8.2.3</span> Step-wise</h3>
<p>The step-wise approach is a combination of forward selection and backward elimination. In this algorithm, the model can either grow or shrink but only ever one term at a time. The modeler uses discretion to add or subtract terms at each iteration, possibly alternating between adding and subtracting, but other paterns are possible as well. The process stops when it’s found that neither adding nor subtracting a term will improve the decision metric (<span class="math inline">\(R_{adj}^2\)</span>, AIC or BIC).</p>
</section>
</section>
<section id="building-examples-in-r" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="building-examples-in-r"><span class="header-section-number">8.3</span> Building Examples in R</h2>
<section id="forward" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="forward"><span class="header-section-number">8.3.1</span> Forward</h3>
<p>In the openintro library you will find a data frame called gifted that contains information on 36 gifted children. Along with their scores for a test of analytical skills, the data frame contains each child’s mother’s and father’s IQs, the age at which the child first said “mommy” or “daddy”, the age when the child first counted to 10 successfully, and the average number of hours per week the child reads with a parent, watches education TV, and watches cartoons.</p>
<p>To build a model working with forward selection and the AIC metric, we can use the <code>step</code> function built into the <code>stats</code> library as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># specify an empty intercept-only model to start</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>mod_start<span class="ot">&lt;-</span><span class="fu">lm</span>(score<span class="sc">~</span><span class="dv">1</span>, <span class="at">data=</span>gifted)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># define the largest model possible as an upper bound on scope </span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>mod_full<span class="ot">&lt;-</span><span class="fu">lm</span>(score<span class="sc">~</span>., <span class="at">data=</span>gifted)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># specifying k=2 indicates using AIC.  Each step will be printed out.</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(mod_start, <span class="at">scope=</span><span class="fu">list</span>(<span class="at">lower=</span>mod_start, <span class="at">upper=</span>mod_full), </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">direction=</span><span class="st">"forward"</span>, <span class="at">k=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=111.33
score ~ 1

           Df Sum of Sq    RSS     AIC
+ motheriq  1   244.838 505.47  99.111
+ count     1   222.211 528.09 100.687
+ read      1   206.958 543.35 101.712
+ edutv     1   102.861 647.44 108.023
+ speak     1    53.846 696.46 110.650
+ cartoons  1    45.074 705.23 111.100
&lt;none&gt;                  750.31 111.331
+ fatheriq  1    26.542 723.76 112.034

Step:  AIC=99.11
score ~ motheriq

           Df Sum of Sq    RSS     AIC
+ read      1   227.205 278.26  79.622
+ count     1   211.162 294.31  81.640
+ speak     1    38.747 466.72  98.240
+ fatheriq  1    30.712 474.76  98.854
+ edutv     1    27.814 477.65  99.073
&lt;none&gt;                  505.47  99.111
+ cartoons  1     2.272 503.20 100.949

Step:  AIC=79.62
score ~ motheriq + read

           Df Sum of Sq    RSS    AIC
+ fatheriq  1    43.605 234.66 75.486
&lt;none&gt;                  278.26 79.622
+ speak     1    11.834 266.43 80.057
+ edutv     1     5.904 272.36 80.850
+ count     1     3.617 274.65 81.151
+ cartoons  1     0.563 277.70 81.549

Step:  AIC=75.49
score ~ motheriq + read + fatheriq

           Df Sum of Sq    RSS    AIC
&lt;none&gt;                  234.66 75.486
+ speak     1   12.5784 222.08 75.503
+ edutv     1    9.7910 224.87 75.952
+ count     1    4.3398 230.32 76.814
+ cartoons  1    0.8398 233.82 77.357</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ motheriq + read + fatheriq, data = gifted)

Coefficients:
(Intercept)     motheriq         read     fatheriq  
    44.3656       0.4282      12.7663       0.3215  </code></pre>
</div>
</div>
<p>Now let’s examine each step of the output above. We specified in the <code>step</code> command that we wanted to begin with an empty intercept-only model and that the biggest model that could be considered is the full model with all predictors available in the <code>gifted</code> data frame.</p>
<p>At the start, our intercept-only model has an AIC of 111.33, and the first table in the output tells us the RSS (Residual Sum of Squares or SSError) and AIC for models that include the intercept plus each possible term one by one; each term gets a new row in the table. In the first round, R found that adding <code>motheriq</code> to the intercept produced an AIC of 99.111, adding <code>count</code> led to an AIC of 100.687, adding <code>read</code> led to an AIC of 101.712… and so on through to adding <code>fatheriq</code> making for an AIC of 112.034, an actual increase over the baseline start of 111.33. Since lower AIC is better, <code>motheriq</code> gets added to the model, and the second round begins.</p>
<p>Step two begins with the <code>score~motheriq</code> model. An intercept is included but not explicitly stated here. The table shows the results from adding each possible remaining predictor to the score to the model and finds that adding in <code>read</code> is the most helpful and will decrease the model AIC to 79.622.</p>
<p>Two more rounds of forward selection continue. The third round examines adding another term to the <code>score~motheriq+read</code> model, and selects adding in <code>fatheriq</code>. Round four looks to add to the <code>score~motheriq+read+fatheriq</code> model, but discovers adding any of the remaining possible terms will result in a higher AIC so the search ends and the <code>score~motheriq+read+fatheriq</code> is returned as the final model.</p>
</section>
<section id="backward" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="backward"><span class="header-section-number">8.3.2</span> Backward</h3>
<p>What if the backward elimination approach is taken? Same <code>gifted</code> data as used in the forward selection example, but now let’s start with the full model and remove terms one at a time until all <span class="math inline">\(\hat\beta\)</span> p-values are below <span class="math inline">\(\alpha=0.05\)</span>.</p>
<p>We’ll start by checking the VIFs to determine if high multicollinearity should be taken care of first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(mod_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>fatheriq motheriq    speak    count     read    edutv cartoons 
1.196214 1.172998 1.182755 6.886769 6.896808 8.214684 8.373075 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_full)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate  Std. Error    t value     Pr(&gt;|t|)
(Intercept) 75.5084856 24.02617507  3.1427593 3.934153e-03
fatheriq     0.2524925  0.13756072  1.8354988 7.707469e-02
motheriq     0.4000681  0.07290507  5.4875205 7.328886e-06
speak        0.1876429  0.14766697  1.2707168 2.142862e-01
count        0.2064897  0.26631214  0.7753673 4.446222e-01
read         7.5440549  5.58640059  1.3504321 1.876921e-01
edutv       -4.2024429  2.24503495 -1.8718831 7.170324e-02
cartoons    -3.3389901  2.01808208 -1.6545363 1.091872e-01</code></pre>
</div>
</div>
<p>Since time spent watching educational tv and time spent watching cartoons are strongly correlated with each other (correlation of -0.9234), it is not surprising that the two have high VIFs. For step one, we’ll remove <code>cartoons</code> because of the two, it is the one with the higher <span class="math inline">\(\hat\beta\)</span> p-value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>mod_2<span class="ot">&lt;-</span><span class="fu">lm</span>(score<span class="sc">~</span>fatheriq<span class="sc">+</span>motheriq<span class="sc">+</span>speak<span class="sc">+</span>count<span class="sc">+</span>read<span class="sc">+</span>edutv, <span class="at">data=</span>gifted)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(mod_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>fatheriq motheriq    speak    count     read    edutv 
1.016676 1.154849 1.158823 6.650745 6.759192 1.217195 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_2)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate  Std. Error    t value     Pr(&gt;|t|)
(Intercept) 49.8812173 18.90916625  2.6379385 0.0132717059
fatheriq     0.3406675  0.13056188  2.6092414 0.0142021633
motheriq     0.3850639  0.07447438  5.1704205 0.0000157951
speak        0.2223968  0.15048032  1.4779129 0.1502106664
count        0.2880610  0.26943473  1.0691311 0.2938293264
read         6.2384283  5.69364778  1.0956822 0.2822341840
edutv       -0.7741723  0.88969865 -0.8701512 0.3913636419</code></pre>
</div>
</div>
<p>In our model without <code>cartoons</code>, <code>read</code> and <code>count</code> still have VIFs greater than 5. They are strongly positively correlated (0.9103) so even though <code>edutv</code> has the highest p-value, I’ll drop <code>count</code> this round since it has the higher p-value between <code>count</code> and <code>read</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>mod_3<span class="ot">&lt;-</span><span class="fu">lm</span>(score<span class="sc">~</span>fatheriq<span class="sc">+</span>motheriq<span class="sc">+</span>speak<span class="sc">+</span>read<span class="sc">+</span>edutv, <span class="at">data=</span>gifted)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(mod_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>fatheriq motheriq    speak     read    edutv 
1.016335 1.136772 1.054395 1.072252 1.190811 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_3)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) 47.0554351 18.76811965  2.507200 1.781474e-02
fatheriq     0.3381140  0.13085088  2.583965 1.488079e-02
motheriq     0.3950256  0.07406516  5.333487 9.083768e-06
speak        0.1741009  0.14388176  1.210028 2.357167e-01
read        11.8220180  2.27313104  5.200764 1.321418e-05
edutv       -0.9142163  0.88209867 -1.036411 3.082929e-01</code></pre>
</div>
</div>
<p>High multicollinearity is all cleared up now so the focus can be solely on p-values. Now we’ll drop <code>edutv</code> for having the highest p-value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>mod_4<span class="ot">&lt;-</span><span class="fu">lm</span>(score<span class="sc">~</span>fatheriq<span class="sc">+</span>motheriq<span class="sc">+</span>speak<span class="sc">+</span>read, <span class="at">data=</span>gifted)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_4)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate  Std. Error  t value     Pr(&gt;|t|)
(Intercept) 42.7092528 18.31549501 2.331865 2.637951e-02
fatheriq     0.3242503  0.13032091 2.488091 1.842563e-02
motheriq     0.4207323  0.06987185 6.021485 1.154340e-06
speak        0.1898180  0.14325136 1.325070 1.948325e-01
read        12.2089372  2.24494494 5.438413 6.108775e-06</code></pre>
</div>
</div>
<p>Next to drop is speak.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>mod_5<span class="ot">&lt;-</span><span class="fu">lm</span>(score<span class="sc">~</span>fatheriq<span class="sc">+</span>motheriq<span class="sc">+</span>read, <span class="at">data=</span>gifted)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_5)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate  Std. Error  t value     Pr(&gt;|t|)
(Intercept) 44.3655659 18.48732491 2.399783 2.239759e-02
fatheriq     0.3214775  0.13183396 2.438503 2.047870e-02
motheriq     0.4282474  0.07045893 6.077973 8.662970e-07
read        12.7663191  2.23107427 5.722050 2.430603e-06</code></pre>
</div>
</div>
<p>And now we’ll stop because all remaining terms have a p-value smaller than our <span class="math inline">\(\alpha=0.05\)</span> threshold. The final model of <code>score~fatheriq+motheriq+read</code> matches the one obtained using AIC and forward selection, but that need not be the case. In fact, let’s look at what happens if we were to perform our backward elimination without multicollinearity checks along the way.</p>
<p>Our first step would have us remove <code>count</code> because it’s p-value of 0.4446 is the highest in <code>mod_full</code>. So step two would now be:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>mod_2<span class="ot">&lt;-</span><span class="fu">lm</span>(score<span class="sc">~</span>fatheriq<span class="sc">+</span>motheriq<span class="sc">+</span>speak<span class="sc">+</span>read<span class="sc">+</span>edutv<span class="sc">+</span>cartoons, <span class="at">data=</span>gifted)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_2)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) 75.7756404 23.85794658  3.176117 3.526914e-03
fatheriq     0.2430752  0.13607806  1.786292 8.451231e-02
motheriq     0.4082659  0.07163665  5.699121 3.646928e-06
speak        0.1511945  0.13901910  1.087581 2.857370e-01
read        11.5226177  2.19353467  5.252991 1.255677e-05
edutv       -4.5968140  2.17157275 -2.116813 4.297596e-02
cartoons    -3.6286687  1.96951508 -1.842417 7.566028e-02</code></pre>
</div>
</div>
<p>Then <code>speak</code> is removed…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>mod_3<span class="ot">&lt;-</span><span class="fu">lm</span>(score<span class="sc">~</span>fatheriq<span class="sc">+</span>motheriq<span class="sc">+</span>read<span class="sc">+</span>edutv<span class="sc">+</span>cartoons, <span class="at">data=</span>gifted)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_3)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) 79.0467761 23.73960954  3.329742 2.312701e-03
fatheriq     0.2373610  0.13639031  1.740307 9.205533e-02
motheriq     0.4121118  0.07176701  5.742357 2.870557e-06
read        11.9013189  2.17231039  5.478646 6.030978e-06
edutv       -4.8881415  2.16154516 -2.261411 3.114315e-02
cartoons    -3.8202332  1.96759143 -1.941578 6.163171e-02</code></pre>
</div>
</div>
<p>Then <code>fatheriq</code> is removed…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>mod_4<span class="ot">&lt;-</span><span class="fu">lm</span>(score<span class="sc">~</span>motheriq<span class="sc">+</span>read<span class="sc">+</span>edutv<span class="sc">+</span>cartoons, <span class="at">data=</span>gifted)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_4)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) 112.5034019 14.37637560  7.825575 7.855003e-09
motheriq      0.4177214  0.07400329  5.644633 3.383735e-06
read         11.6036137  2.23529988  5.191077 1.241780e-05
edutv        -6.0534053  2.12140697 -2.853486 7.638249e-03
cartoons     -5.1125813  1.88075148 -2.718372 1.064514e-02</code></pre>
</div>
</div>
<p>And now since all p-values are below our 0.05 threshold we would stop with the <code>score~motheriq+read+edutv+cartoons</code> model. Checking at this stopping point for multicollinearity would make us then question having both <code>edutv</code> and <code>cartoons</code> in the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(mod_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>motheriq     read    edutv cartoons 
1.143219 1.044483 6.938065 6.878850 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>mod_5<span class="ot">&lt;-</span><span class="fu">lm</span>(score<span class="sc">~</span>motheriq<span class="sc">+</span>read<span class="sc">+</span>edutv, <span class="at">data=</span>gifted)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ motheriq + read + edutv, data = gifted)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.6035 -1.7634 -0.0054  1.4456  6.7931 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 87.74186   12.18228   7.202 3.52e-08 ***
motheriq     0.40044    0.08076   4.959 2.24e-05 ***
read        11.99889    2.44313   4.911 2.57e-05 ***
edutv       -0.79303    0.95214  -0.833    0.411    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.917 on 32 degrees of freedom
Multiple R-squared:  0.637, Adjusted R-squared:  0.603 
F-statistic: 18.72 on 3 and 32 DF,  p-value: 3.405e-07</code></pre>
</div>
</div>
<p>Removing cartoons as having the higher of the two p-values leaves us with <code>score~motheriq+read+edutv</code>, a model that’s a bit different from the one found through forward selection with AIC and backward elimination with multicollinearity considered up front.</p>
</section>
<section id="step-wise-1" class="level3" data-number="8.3.3">
<h3 data-number="8.3.3" class="anchored" data-anchor-id="step-wise-1"><span class="header-section-number">8.3.3</span> Step-wise</h3>
<p>Lastly we’ll use the same step function used in our forward selection example to perform step-wise model selection using BIC. The scope of models to be considered is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we begin with the mod_5 at the end of the backward elimination example.</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># scope ranges from intercept-only to the full model as before</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co"># specifying k=ln(n) indicates using BIC to make decisions</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>stepwise<span class="ot">&lt;-</span><span class="fu">step</span>(mod_5, <span class="at">scope=</span><span class="fu">list</span>(<span class="at">lower=</span>mod_start, <span class="at">upper=</span>mod_full), </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">direction=</span><span class="st">"both"</span>, <span class="at">k=</span><span class="fu">log</span>(<span class="fu">nrow</span>(gifted)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=87.18
score ~ motheriq + read + edutv

           Df Sum of Sq    RSS     AIC
+ cartoons  1    52.426 219.93  83.070
+ fatheriq  1    47.491 224.87  83.869
- edutv     1     5.904 278.26  84.372
&lt;none&gt;                  272.36  87.184
+ speak     1    10.237 262.12  89.388
+ count     1     2.686 269.67  90.410
- read      1   205.296 477.65 103.824
- motheriq  1   209.278 481.64 104.123

Step:  AIC=83.07
score ~ motheriq + read + edutv + cartoons

           Df Sum of Sq    RSS     AIC
&lt;none&gt;                  219.93  83.070
+ fatheriq  1    20.167 199.77  83.192
+ speak     1     6.877 213.06  85.510
+ count     1     0.475 219.46  86.576
- cartoons  1    52.426 272.36  87.184
- edutv     1    57.767 277.70  87.883
- read      1   191.180 411.11 102.007
- motheriq  1   226.047 445.98 104.937</code></pre>
</div>
</div>
<p>The output looks much like the output created in our forward selection case with one major difference: at each step the table of possible decisions includes both + terms and - terms. In step 1 the function considers adding <code>cartoons</code>, <code>fatheriq</code>, <code>speak</code>, or <code>count</code>, and also taking away <code>edutv</code>, <code>read</code>, or <code>motheriq</code>. Though labeled “AIC” the last column is actually a calculated BIC because we specified <code>k=log(n)</code>. In R’s <code>step</code> function, the value of k specifies the multiplier to be put with the (p+2) measure of model size:</p>
<p><span class="math display">\[
step's \:AIC=k(p+2)-2ln(\hat L)
\]</span></p>
<p>This means <em>k=2</em> indicates you want traditional AIC, and <em>k=ln(n)</em> indicates BIC. Remember <code>log(n)</code> in R is using natural log.</p>
</section>
</section>
<section id="best-model-of-size-p" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="best-model-of-size-p"><span class="header-section-number">8.4</span> Best model of size p</h2>
<p>In the <code>leaps</code> library you can find a helpful function called <code>regsubsets</code>. The <code>regsubsets</code> function allows you to have R search every possible model with p predictors and tell you which is best.</p>
<p>Here is an example with our gifted data where regsubsets is asked to consider models ranging from having one predictor (in addition to an intercept) up to four predictors. As inputs we provide the form of the full model, the data set, <code>nbest</code> tells R how many “best” models we want of each size, and <code>nvmax</code> tells R how large a model we want to work up to.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>best_mods<span class="ot">&lt;-</span><span class="fu">regsubsets</span>(score<span class="sc">~</span>., <span class="at">data=</span>gifted, <span class="at">nbest=</span><span class="dv">1</span>, <span class="at">nvmax=</span><span class="dv">4</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(best_mods)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(score ~ ., data = gifted, nbest = 1, nvmax = 4)
7 Variables  (and intercept)
         Forced in Forced out
fatheriq     FALSE      FALSE
motheriq     FALSE      FALSE
speak        FALSE      FALSE
count        FALSE      FALSE
read         FALSE      FALSE
edutv        FALSE      FALSE
cartoons     FALSE      FALSE
1 subsets of each size up to 4
Selection Algorithm: exhaustive
         fatheriq motheriq speak count read edutv cartoons
1  ( 1 ) " "      "*"      " "   " "   " "  " "   " "     
2  ( 1 ) " "      "*"      " "   " "   "*"  " "   " "     
3  ( 1 ) "*"      "*"      " "   " "   "*"  " "   " "     
4  ( 1 ) "*"      "*"      "*"   "*"   " "  " "   " "     </code></pre>
</div>
</div>
<p>From the top section of this output you can see there are “forced in” and “forced out” options we did not apply to any of the potential independent variables. The lower section then gives the results. The row labeled “1” has an asterisk under <code>motheriq</code> indicating the best one-predictor model uses <code>motheriq</code>. The row labeled “2” has asterisks for <code>motheriq</code> and <code>read</code> telling us the best two-predictor model includes those terms. The best three-predictor model is shown to be <code>score~fatheriq+motheriq+read</code>, and the best four–predictor model found was <code>score~fatheriq+motheriq+speak+count</code>.</p>
<p>Notice the best three-predictor model is not simply a subset of the best four-predictor model. While our forward selection, backward elimination, and stepwise models change only one term at a time making each successive model have only one variable different, the work done by <code>regsubsets</code> is exhaustive and doesn’t require one-at-a-time changes.</p>
</section>
<section id="lasso-regression" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="lasso-regression"><span class="header-section-number">8.5</span> Lasso Regression</h2>
<p>Recall from way back in Chapter 2 that our best linear fit solution comes from wanting to set the <span class="math inline">\(\hat\beta_i\)</span> values in such a way that <span class="math inline">\(\sum (y_i-\hat{y_i})^2\)</span> is minimized. The lasso technique modifies this goal so that instead we minimize:</p>
<p><span id="eq-lasso"><span class="math display">\[
\sum_{i=1}^{n} (y_i-\hat y_i)^2 + \lambda \sum_{j=1}^{p}|{\beta_j}|
\tag{8.1}\]</span></span></p>
<p>With this change, we are making the decision that minimizing the sum of squared errors is important, but we also want to minimize the sum of the absolute value of our <span class="math inline">\(\beta\)</span> parameters weighted by a <span class="math inline">\(\lambda\)</span> tuning parameter. The value in doing this, is that now we can start with all possible independent variables and see which get eliminated through a <span class="math inline">\(\hat\beta=0\)</span> fit.</p>
<section id="in-r-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r-2">In R</h3>
<p>We’ll apply this approach in R to our gifted data using the <code>glmnet</code> function in the <code>glmnet</code> library.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first need our data in format of x and y matrices</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>mod_x<span class="ot">&lt;-</span><span class="fu">as.matrix</span>(gifted[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>mod_y<span class="ot">&lt;-</span><span class="fu">as.matrix</span>(gifted[,<span class="dv">1</span>])</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="co"># use cross validation to explore different values of lambda</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>step1<span class="ot">&lt;-</span><span class="fu">cv.glmnet</span>(mod_x, mod_y, <span class="at">alpha=</span><span class="dv">1</span>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(step1<span class="sc">$</span>glmnet.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter8_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This first plot looks at the values of the <span class="math inline">\(\beta\)</span> coefficients over a wide range of <span class="math inline">\(\lambda\)</span> values. Each <span class="math inline">\(\beta\)</span> has one colored line associated with it. The different considered<span class="math inline">\(\lambda\)</span>s are along the x-axis, but in the form of <span class="math inline">\(-log(\lambda)\)</span>, and the y-axis indicates the value of the <span class="math inline">\(\beta\)</span>s for each corresponding <span class="math inline">\(\lambda\)</span>. Along the top of the plot the number of non-zero <span class="math inline">\(\beta\)</span> coefficients is shown.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(step1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Chapter8_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the mean-squared error for our model under various values of <span class="math inline">\(\lambda\)</span>. Vertical reference lines are drawn at the minimum mean-squared error, and at the minimum plus one standard error. The <span class="math inline">\(\lambda\)</span>s that correspond to each of these key values are retrievable through <code>step1$lambda.min</code> and <code>step1$lambda.1se</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>step1<span class="sc">$</span>lambda.min</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2115333</code></pre>
</div>
</div>
<p>Then we can fit the model using the identified best <span class="math inline">\(\lambda\)</span> and see which coefficients are non-zero:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>step2<span class="ot">&lt;-</span><span class="fu">glmnet</span>(mod_x, mod_y, <span class="at">alpha=</span><span class="dv">1</span>, <span class="at">lambda=</span>step1<span class="sc">$</span>lambda.min)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>lasso.coef<span class="ot">&lt;-</span><span class="fu">predict</span>(step2, <span class="at">type=</span><span class="st">"coefficients"</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>lasso.coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>8 x 1 sparse Matrix of class "dgCMatrix"
                    s0
(Intercept) 63.4282931
fatheriq     0.2681240
motheriq     0.3592196
speak        0.1696803
count        0.2590080
read         5.8841220
edutv       -0.5542266
cartoons     .        </code></pre>
</div>
</div>
<p>If not satisfied with only eliminating cartoons, we could change to a larger, non-optimal lambda:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>step2<span class="ot">&lt;-</span><span class="fu">glmnet</span>(mod_x, mod_y, <span class="at">alpha=</span><span class="dv">1</span>, <span class="at">lambda=</span><span class="fl">1.5</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>lasso.coef<span class="ot">&lt;-</span><span class="fu">predict</span>(step2, <span class="at">type=</span><span class="st">"coefficients"</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>lasso.coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>8 x 1 sparse Matrix of class "dgCMatrix"
                     s0
(Intercept) 130.0439277
fatheriq      .        
motheriq      0.1734218
speak         .        
count         0.1340442
read          2.1009536
edutv         .        
cartoons      .        </code></pre>
</div>
</div>
<p>And here we see <code>motheriq</code>, <code>count</code>, and <code>read</code> are the three terms selected as having a non-zero coefficient with <span class="math inline">\(\lambda=1.5\)</span>. To use lasso strictly as a model selection tool, from here you would then return to the lm function to fit a model with these three terms are base any predictions on the <span class="math inline">\(\hat\beta\)</span>s that result from simply fitting the least-squares criterion, not that seen in <a href="#eq-lasso" class="quarto-xref">Equation&nbsp;<span>8.1</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>mod_result<span class="ot">&lt;-</span><span class="fu">lm</span>(score<span class="sc">~</span>motheriq<span class="sc">+</span>count<span class="sc">+</span>read, <span class="at">data=</span>gifted)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_result)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) 85.3970316 11.39507108 7.4942079 1.565612e-08
motheriq     0.4157893  0.07710859 5.3922568 6.345091e-06
count        0.1820829  0.28048936 0.6491617 5.208663e-01
read         8.9042595  5.88322934 1.5134986 1.399682e-01</code></pre>
</div>
</div>
</section>
</section>
<section id="principal-components-analysis-pca" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="principal-components-analysis-pca"><span class="header-section-number">8.6</span> Principal Components Analysis (PCA)</h2>
<p>Now we’re going to consider a much larger data set: the <code>bdims</code> data frame in the <code>openintro</code> library contains 25 measures on 507 physically active adults. In addition to gender, age, weight, and height, we have access to hip girth, bicep girth, knee diameter, and all kinds of body measurements. It’s great information, but as you might suspect these measurements are often highly correlated with each other. Larger hip girths tend to go with larger waists, small ankles make you more likely to have smaller wrists, and so on.</p>
<p>Principal Components Analysis is a way we can incorporate much of the valuable information offered by these 21 body measurements, without making our model have 21 separate slopes and a host of multicollinearity issues. How?</p>
<p>Let’s start smaller and focus on two of our body measurements: <code>hip_gi</code>, the hip girth as measured at the same level as <code>bit_di</code>, the bitrochanteric diameter. Bitrochanteric diameter is basically hip width at the top of the femur but below the pelvis. Obviously these two measurements should be correlated and they are. Limiting to only the 247 men in the <code>bdims</code> data frame, the two hip measurements are plotted here in <a href="#fig-hips" class="quarto-xref">Figure&nbsp;<span>8.2</span></a>.</p>
<div class="cell">
<div id="fig-hips" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hips-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="fig-hips" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-hips-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter8_files/figure-html/fig-hips-1.png" class="img-fluid figure-img" data-ref-parent="fig-hips" width="384">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-hips-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Original data
</figcaption>
</figure>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hips-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: Male Hip Measurements
</figcaption>
</figure>
</div>
</div>
<p>Now look at the plot with the regression line overlaid and think about rotating the entire scatter plot to right a bit so that regression line was the new x-axis. Go ahead, pick up your book or screen (or turn your head) and rotate the graph so the blue line is our new horizontal. If you knew where along that new x-axis a person lied, you’d know a lot about their hip size. You’d have a combination of hip girth and hip diameter information with just that one blue-axis variable. The vertical variation up and down from that line is the relatively small amount of information you’re giving up by only using one variable instead of the original two.</p>
<p>We could repeat this process over and over with pairs of body measurements we know are related, at each point picking the one-dimensional combination of them and effectively cutting our model size in half while giving up relatively little. But 1) that’s time consuming and 2) what if we don’t have the proper knowledge to know which terms to pair?</p>
<p>Stop and think about how that blue line does such a good job simplifying the two dimensions into one main direction of variability and then one minor direction of variability. What if we could take our full 21 dimensions of body measurements and get the computer to tell us the axes that align with the highest variability and the least variability? That is what we can do with <strong><em>principal components analysis</em></strong>, often referred to simply as <strong><em>PCA</em></strong>.</p>
<p>The linear algebra that’s driving this change in basis is beyond our scope here, but instead we will focus on how to apply the method in R.</p>
<section id="in-r-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r-3">In R</h3>
<p>First, the data must be numeric in nature. For our body measurements, we’ll look only at women, and only at the first 21 columns which cover <code>bia_di</code> (biacromial diameter) through <code>wri_gi</code> (wrist girth). There are a few different functions in R that will perform PCA, but we’ll use the <code>prcomp</code> option that comes in the <code>stats</code> library.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>womens_bdims<span class="ot">&lt;-</span>bdims[bdims<span class="sc">$</span>sex<span class="sc">==</span><span class="dv">0</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">21</span>]</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="co"># or if you prefer:</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>womens_bdims<span class="ot">&lt;-</span>bdims <span class="sc">|&gt;</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex<span class="sc">==</span><span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(bia_di<span class="sc">:</span>wri_gi)</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>pca_body<span class="ot">&lt;-</span><span class="fu">prcomp</span>(womens_bdims, <span class="at">scale.=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that when <code>prcomp</code> is called, the <code>scale.=TRUE</code> is added in. What this does is tell R that before finding the axes of highest variability, the data should be scaled. This keeps us from labeling the dimensions that just happen to have bigger numbers from dominating the findings. If all body measurements were taken in cm but we transformed knee diameter into mm, we’d think a difference of 100 in the knee measurement was huge and a difference of 10cm in a waist was tiny. The <code>scale.=TRUE</code> takes each column and converts it to z-scores using the column means and standard deviations. This was a 3-standard deviation high measure on calf girth gets the exact same attention as a 3-standard deviation high measure on ankle girth. Always scale in PCA.</p>
<p><a href="#fig-pcares1" class="quarto-xref">Figure&nbsp;<span>8.3</span></a> shows the first four principal components. The <code>prcomp</code> function will create as many principal components (new axes) as there are original dimensions to your data. They are ordered based on the amount of variability they can explain. Notice that every plot in the scatter plot matrix looks like just a random blob. That will always happen as these new axes will be uncorrelated with each other by design.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pcares1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pcares1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter8_files/figure-html/fig-pcares1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pcares1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.3: PCA Results
</figcaption>
</figure>
</div>
</div>
</div>
<p>A <code>biplot</code> can be used to get a sense of how the original columns relate to the new principal components. Two biplots showing PC1 vs.&nbsp;PC2 and PC3 vs.&nbsp;PC4 are below in <a href="#fig-pcares2" class="quarto-xref">Figure&nbsp;<span>8.4</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">biplot</span>(pca_body)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="fu">biplot</span>(pca_body, <span class="at">choices=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-pcares2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pcares2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter8_files/figure-html/fig-pcares2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pcares2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.4: PCA Results
</figcaption>
</figure>
</div>
</div>
</div>
<p>Both of these <code>biplots</code> are a bit hard to read because there are 21 red vectors all on top of each other. The first gives some discernable information though. It shows that PC1 involves a negative multiple of every column, while PC2 looks to be about half positive and half negative. The numeric information for how the original columns map to the principal components is given in the <code>$rotation</code> element of our completed <code>prcomp</code> object.</p>
<p>Here are the mappings for the first two principal components, rounded to five decimal places. They confirm the all-negative loadings for PC1 and the roughly even positive/negative split for PC2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(pca_body<span class="sc">$</span>rotation[,<span class="dv">1</span>],<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  bia_di   bii_di   bit_di   che_de   che_di   elb_di   wri_di   kne_di 
-0.16001 -0.15629 -0.21022 -0.17278 -0.20168 -0.20772 -0.19393 -0.23672 
  ank_di   sho_gi   che_gi   wai_gi   nav_gi   hip_gi   thi_gi   bic_gi 
-0.17357 -0.23440 -0.24326 -0.23461 -0.22822 -0.25381 -0.23532 -0.24366 
  for_gi   kne_gi   cal_gi   ank_gi   wri_gi 
-0.25137 -0.24002 -0.22807 -0.20682 -0.22877 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(pca_body<span class="sc">$</span>rotation[,<span class="dv">2</span>],<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  bia_di   bii_di   bit_di   che_de   che_di   elb_di   wri_di   kne_di 
 0.31718 -0.05449  0.06264 -0.32902  0.05383  0.29060  0.39074  0.13547 
  ank_di   sho_gi   che_gi   wai_gi   nav_gi   hip_gi   thi_gi   bic_gi 
 0.31147 -0.03461 -0.18167 -0.32502 -0.29562 -0.18830 -0.20851 -0.19328 
  for_gi   kne_gi   cal_gi   ank_gi   wri_gi 
 0.00609  0.03437  0.04863  0.16233  0.23538 </code></pre>
</div>
</div>
<p>Interested in how much of the total variability can be seen in each principal component? That information is seen in the <code>$sdev</code> element of the <code>prcomp</code> object and can be seen in a bar chart with the plot command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert standard deviations to variance by squaring</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>variances<span class="ot">&lt;-</span>pca_body<span class="sc">$</span>sdev<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="co"># look at variance for first 8 components, rounded</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(variances[<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>],<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.3825  1.6555  1.2828  1.0451  0.8028  0.5475  0.4608  0.4358</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># proportion of total variance for first 8 components, rounded</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(variances[<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>]<span class="sc">/</span><span class="fu">sum</span>(variances),<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5896 0.0788 0.0611 0.0498 0.0382 0.0261 0.0219 0.0208</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># see plot of variance per component</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pca_body)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-pcares3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pcares3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter8_files/figure-html/fig-pcares3-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pcares3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.5: Component Variance Plot
</figcaption>
</figure>
</div>
</div>
</div>
<p>But what does any of this have to do with regression? Well, now that we have our principal components we can use them as predictors in our model to maximize the information from our data set while minimizing the number of <span class="math inline">\(\beta\)</span> parameters that need estimating.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create BMI outcome to estimate with the measurements</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>bmi<span class="ot">&lt;-</span>bdims<span class="sc">$</span>wgt<span class="sc">/</span>(bdims<span class="sc">$</span>hgt<span class="sc">/</span><span class="dv">100</span>)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="co">#limit to only the women</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>bmi_f<span class="ot">&lt;-</span>bmi[bdims<span class="sc">$</span>sex<span class="sc">==</span><span class="dv">0</span>]</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a><span class="co">#fit model with first seven principal components</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>mod_bmi<span class="ot">&lt;-</span><span class="fu">lm</span>(bmi_f<span class="sc">~</span>pca_body<span class="sc">$</span>x[,<span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>])</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a><span class="co">#look at model summary</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_bmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi_f ~ pca_body$x[, 1:7])

Residuals:
    Min      1Q  Median      3Q     Max 
-3.8904 -0.7937 -0.0327  0.7054  4.1316 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          22.27793    0.07581 293.853  &lt; 2e-16 ***
pca_body$x[, 1:7]PC1 -0.77013    0.02159 -35.677  &lt; 2e-16 ***
pca_body$x[, 1:7]PC2 -0.88505    0.05904 -14.992  &lt; 2e-16 ***
pca_body$x[, 1:7]PC3  0.35202    0.06707   5.249 3.25e-07 ***
pca_body$x[, 1:7]PC4 -0.22522    0.07430  -3.031  0.00269 ** 
pca_body$x[, 1:7]PC5 -0.05495    0.08478  -0.648  0.51751    
pca_body$x[, 1:7]PC6  0.24817    0.10266   2.417  0.01634 *  
pca_body$x[, 1:7]PC7 -0.11019    0.11190  -0.985  0.32573    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.222 on 252 degrees of freedom
Multiple R-squared:  0.8595,    Adjusted R-squared:  0.8556 
F-statistic: 220.2 on 7 and 252 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>This model summary shows us that just because one component covers more variability than another, doesn’t mean that component is more important when it comes to predicting our outcome. PC6 covers only 2.61% of the total variability compared to PC5’s 3.82%, but when it comes to predicting a person’s BMI PC6 is more helpful than PC5. Since PC1 and PC2 are so strongly related to BMI, it turns out a model with just those two predictors has an <span class="math inline">\(R_{adj}^2=0.8337\)</span>.- not bad for a 3-<span class="math inline">\(\beta\)</span> model on a complex problem.</p>
<p>You can run forward selection, backward elimination, or step-wise building algorithms on the principal components just as you would the raw data - but now with the advantage of not having multicollinearity to navigate.</p>
<p>PCA isn’t without it’s downsides. Using this type of approach and model might be very powerful, but it isn’t nearly as interpretable as a model built on the original data. Depending on the context of the work, interpretability might take a back seat to predictive power which makes PCA a strong option. Also, sometimes looking at the PCA loadings themselves can provide insight into the interdependencies and relationships within your data.</p>
<p>Bottom line: PCA is a powerful tool to have in your tool box, but it shouldn’t be the first tool you turn to when fitting a model.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Chapter7.html" class="pagination-link" aria-label="Go Bigger">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Go Bigger</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Chapter9.html" class="pagination-link" aria-label="Well that's weird">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Well that’s weird</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>