<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Make it Work – Intro Regression In R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Chapter6.html" rel="next">
<link href="./Chapter4.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0615981f0f11b1670b07f78b9ae6e573.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Chapter5.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Make it Work</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Intro Regression In R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualize the Relationship</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Add a Line</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">How sure are you?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Assumptions Were Made</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter5.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Make it Work</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Zeros and Ones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Go Bigger</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Building and Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Well that’s weird</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-simple-transformations" id="toc-sec-simple-transformations" class="nav-link active" data-scroll-target="#sec-simple-transformations"><span class="header-section-number">5.1</span> Simple Transformations</a>
  <ul class="collapse">
  <li><a href="#in-r" id="toc-in-r" class="nav-link" data-scroll-target="#in-r">In R</a></li>
  </ul></li>
  <li><a href="#log-log-transformation" id="toc-log-log-transformation" class="nav-link" data-scroll-target="#log-log-transformation"><span class="header-section-number">5.2</span> Log-Log Transformation</a></li>
  <li><a href="#box-cox-transformation" id="toc-box-cox-transformation" class="nav-link" data-scroll-target="#box-cox-transformation"><span class="header-section-number">5.3</span> Box-Cox Transformation</a>
  <ul class="collapse">
  <li><a href="#in-r-1" id="toc-in-r-1" class="nav-link" data-scroll-target="#in-r-1">In R</a></li>
  </ul></li>
  <li><a href="#unit-change" id="toc-unit-change" class="nav-link" data-scroll-target="#unit-change"><span class="header-section-number">5.4</span> Unit change</a></li>
  <li><a href="#on-your-own-all-transformations" id="toc-on-your-own-all-transformations" class="nav-link" data-scroll-target="#on-your-own-all-transformations">On Your Own, All Transformations</a></li>
  <li><a href="#weighted-least-squares" id="toc-weighted-least-squares" class="nav-link" data-scroll-target="#weighted-least-squares"><span class="header-section-number">5.5</span> Weighted Least Squares</a>
  <ul class="collapse">
  <li><a href="#in-r-2" id="toc-in-r-2" class="nav-link" data-scroll-target="#in-r-2">In R</a></li>
  <li><a href="#on-your-own" id="toc-on-your-own" class="nav-link" data-scroll-target="#on-your-own">On Your Own</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Make it Work</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Just because an assumption or two isn’t met, that doesn’t mean you can’t use regression modeling. It just means you have to work a little harder at it.</p>
<section id="sec-simple-transformations" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-simple-transformations"><span class="header-section-number">5.1</span> Simple Transformations</h2>
<p>We know from the work in <span class="quarto-unresolved-ref">?sec-chap4</span> that the relationship between barometric pressure and boiling point is not quite linear. <a href="#fig-bprev" class="quarto-xref">Figure&nbsp;<span>5.1</span></a> shows the fitted regression line and the resulting fitted vs.&nbsp;residual plot with clear curvature. So what do we do about plots that aren’t linear? We make them linear.</p>
<div id="fig-bprev" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bprev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-bprev" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-bprev-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-bprev-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-bprev-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-bprev" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-bprev-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Data and model fit
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-bprev" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-bprev-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-bprev-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-bprev-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-bprev" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-bprev-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Fitted vs residual plot
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bprev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Boiling point model and residuals
</figcaption>
</figure>
</div>
<p>The idea is this: rather than model boiling point as a function of pressure directly, could we model boiling point as a function of the square-root of pressure? Or log(pressure)? There are four main transformations to consider when trying to make non-linear data more linear: Squares, square-roots, inverses, and logs. Trial and error plus a little exploration might lead you beyond those four, but those are always good places to start.</p>
<div id="fig-4trans" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-4trans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-4trans" style="flex-basis: 25.0%;justify-content: center;">
<div id="fig-4trans-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-4trans-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-4trans-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-4trans" width="144">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-4trans-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Squared
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-4trans" style="flex-basis: 25.0%;justify-content: center;">
<div id="fig-4trans-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-4trans-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-4trans-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-4trans" width="144">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-4trans-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Square-root
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-4trans" style="flex-basis: 25.0%;justify-content: center;">
<div id="fig-4trans-3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-4trans-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-4trans-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-4trans" width="144">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-4trans-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Inverse
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-4trans" style="flex-basis: 25.0%;justify-content: center;">
<div id="fig-4trans-4" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-4trans-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-4trans-4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-4trans" width="144">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-4trans-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Log
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-4trans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Four Tranformations
</figcaption>
</figure>
</div>
<p><a href="#fig-4trans" class="quarto-xref">Figure&nbsp;<span>5.2</span></a> shows the resulting fitted vs.&nbsp;residual plot for each of these transformations applied to pressure. Axis labels are removed because we’re focused only on the shape of the scattered points here and how closely they follow the red line.</p>
<p><a href="#fig-4trans" class="quarto-xref">Figure&nbsp;<span>5.2</span></a> (a) shows that results from modeling boiling point as a function of <span class="math inline">\(pressure^2\)</span> is an even more pronounced parabola than what was originally seen in <a href="#fig-bprev" class="quarto-xref">Figure&nbsp;<span>5.1</span></a>; and <a href="#fig-4trans" class="quarto-xref">Figure&nbsp;<span>5.2</span></a> (c) shows that when boiling point is modeled as a function of <span class="math inline">\(\frac{1}{pressure}\)</span> the parabola flips to become concave up, but does not flatten considerably. From part (b) it is clear that modeling using <span class="math inline">\(\sqrt{pressure}\)</span> is a step in the right direction, but it is the model using <span class="math inline">\(log(pressure)\)</span> in (d) that is the clear winner of these four.</p>
<p>This means that rather than</p>
<p><span class="math display">\[boiling\space point=β_0+β_1pressure+ε\]</span></p>
<p>our model will take the form of</p>
<p><span class="math display">\[boiling\space point=β_0+β_1log(pressure)+ε\]</span></p>
<p>so a plot of our linear fit becomes what is shown in <a href="#fig-bplog" class="quarto-xref">Figure&nbsp;<span>5.3</span></a>. The estimated coefficients of the transformed model come out to be<span class="math inline">\(\hat{β_0}=\)</span> 47.8638 and <span class="math inline">\(\hat{β_1}=\)</span> 48.2467. So now to estimate the boiling point when <span class="math inline">\(pressure=28\)</span> we’d have</p>
<p><span class="math display">\[
47.8638+48.2467\times log(28)=208.6317
\]</span></p>
<div id="fig-bplog" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bplog-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-bplog" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-bplog-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-bplog-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-bplog-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-bplog" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-bplog-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Log pressure plot with model fit
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-bplog" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-bplog-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-bplog-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-bplog-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-bplog" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-bplog-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Fitted vs residual plot
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bplog-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Boiling point log pressure model
</figcaption>
</figure>
</div>
<p>Finding a transformation that makes your linear model work can be a challenge. Maybe your data needs <span class="math inline">\(\frac{1}{x^3}\)</span> or some other less obvious approach - that’s fine. Just start by looking at the shape of the curve you see in your data and consider what function will reverse that shape to create a line. At least one of squares, square-roots, inverses, and logs will usually show some promise and then you can trial and error your way from there to find <span class="math inline">\(x^4\)</span> actually does a better job than <span class="math inline">\(x^2\)</span>.</p>
<p>It is to your advantage though to use a simpler transformation when possible. Why? Interpretation and communication. It’s pretty straight-forward to tell someone that boiling point is linearly related to the log of barometric pressure, but to try explaining that the square-root of boiling point is linearly related the inverse log of barometric pressure.</p>
<p>We’ve transformed X here, but you can also transform Y. Transforming X is generally preferable, because 1)every confidence interval or prediction interval would need to be either transformed back to original units, or interpreted in the revised transformed scale and 2) later we’ll be working with models that include more than one X and transforming Y will impact the relationships for all X at once rather than allowing you to tweak each separately.</p>
<section id="in-r" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r">In R</h3>
<p>When transforming data for linear modeling in R you have two options. First, you can create new variables for use in the <code>lm</code> command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>log_pres<span class="ot">&lt;-</span><span class="fu">log</span>(forbes<span class="sc">$</span>pres)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>model_forbes<span class="ot">&lt;-</span><span class="fu">lm</span>(forbes<span class="sc">$</span>bp<span class="sc">~</span>log_pres)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This takes an extra line of code but sometimes it’s the cleanest approach if you’re using the transformed x for uses beyond your linear model.</p>
<p>Second, you can use the <code>I</code> function inside the <code>lm</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>model_forbes<span class="ot">&lt;-</span><span class="fu">lm</span>(bp<span class="sc">~</span><span class="fu">I</span>(pres<span class="sc">^</span><span class="dv">2</span>), <span class="at">data=</span>forbes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is a bit simpler as it is all in one line and when coupled with a data statment makes it 100% clear that both your X and Y live within the named data frame.</p>
</section>
</section>
<section id="log-log-transformation" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="log-log-transformation"><span class="header-section-number">5.2</span> Log-Log Transformation</h2>
<p>One transformation that is quite common for violations in linearity and Normality involves taking the log of both your X and your Y term. Consider the plots below in <a href="#fig-mammals" class="quarto-xref">Figure&nbsp;<span>5.4</span></a> showing the body and brain weights of 62 mammals. The raw data in fig (a) shows a hard to distinguish clump of points in the lower left corner because African elephant and Asian elephant dwarf the other mammals, but the relationship does not appear to be linear. Part (b) of <a href="#fig-mammals" class="quarto-xref">Figure&nbsp;<span>5.4</span></a> shows the raw data limited only to those mammals weighing less than 1,000kg. You’ll see a hard to distinguish clump still remains since 39 of the 62 mammals are under 5kg, and the points beyond the clump provide further evidence a simple line isn’t going to fit well. Part (c) shows the result when a log transformation is applied to both body and brain weight of all 62 mammals.</p>
<div id="fig-mammals" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mammals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mammals" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-mammals-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mammals-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-mammals-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-mammals" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mammals-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) All raw data
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mammals" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-mammals-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mammals-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-mammals-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-mammals" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mammals-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Only mammals &lt;1000kg
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mammals" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-mammals-3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mammals-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-mammals-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-mammals" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mammals-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Log-log with linear fit
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mammals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Mammal body and brain weight
</figcaption>
</figure>
</div>
<p>Below is the coefficent summary of the log-log model fit.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept) 2.1347887 0.09604339 22.22734 1.183207e-30
log_body    0.7516859 0.02846356 26.40871 9.835792e-35</code></pre>
</div>
</div>
<p>The interpretation of coefficients in a log-log model is a bit special. Whereas in a non-transformed regression fit the slope is interpreted as the mean increase in Y associated with a one-unit increase in X, in the log-log case the slope is the mean percent increase in Y associated with a 1% increase in X. So in the case of mammal brain and body weight, we now see that a 1% increase in a mammal body weight is associated with a roughly 0.75% increase in brain weight.</p>
<p>As an example of how the transformation must be considered when making estimates, we turn to black-tailed deer. A 2023 study of dwarfed black-tailed deer on Blakely Island <span class="citation" data-cites="Geiman2023">(<a href="#ref-Geiman2023" role="doc-biblioref">Geiman and Long 2023</a>)</span> found an average body weight 40.2 kg. So using our model, what would be our best estimate of dwarf black-tailed deer brain weight? First we must take the log of 40.2, and after evaluating the linear fit, we must “un-log” the result to get back to the units of brain weight we care about.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#using predict.lm</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>new_wt<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">log_body=</span><span class="fu">log</span>(<span class="fl">40.2</span>))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>pred_log_brain<span class="ot">&lt;-</span><span class="fu">predict.lm</span>(mod_mammal, new_wt)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(pred_log_brain)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
135.8317 </code></pre>
</div>
</div>
<p>With a 95% confidence interval of:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>pred.ci<span class="ot">&lt;-</span><span class="fu">predict.lm</span>(mod_mammal, new_wt, <span class="at">interval=</span><span class="st">"conf"</span>, <span class="at">level=</span>.<span class="dv">95</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(pred.ci)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit     lwr      upr
1 135.8317 108.833 169.5281</code></pre>
</div>
</div>
<p>The Blakely Island researchers estimated a brain weight of 153.8g based on skull cavity measures of found skulls; not far from our estimate of 135.8g and included in our confidence interval for the mean brain weight that ranges from 108.8g to 169.5g.</p>
</section>
<section id="box-cox-transformation" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="box-cox-transformation"><span class="header-section-number">5.3</span> Box-Cox Transformation</h2>
<p>Real-world data often violate more than just the linearity assumption. Response variables might be skewed, or the variance might increase as the value of the response variable increases (heteroscedasticity). The <strong>Box-Cox transformation</strong> is a family of mathematical functions used to transform non-Normal dependent variables into a form that more closely follows a Normal distribution. The Box-Cox approach can also help in making variances more consistent to meet our homoskedasticity assmption for regression inference.</p>
<p></p><div style="page-break-after: always;"></div> <strong>Box-Cox transformations are especially useful when:</strong><p></p>
<ul>
<li>Your response variable is strictly positive (<span class="math inline">\(y &gt; 0\)</span>).</li>
<li>You observe non-constant variance (heteroscedasticity) in residual plots.</li>
<li>The distribution of your response variable is highly skewed.</li>
<li>Residuals from a fitted model are not normally distributed.</li>
</ul>
<p>The down side to Box-Cox is model interpretability - you’ll definitely have some reverse transforming to do once your model is fit so that people can understand it.</p>
<p>The Box-Cox transformation is defined as follows for a positive variable y:</p>
<p><span class="math display">\[
y^{(\lambda)} =
\begin{cases}
\frac{y^{\lambda} - 1}{\lambda} &amp; \text{if } \lambda \ne 0 \\
\ln(y) &amp; \text{if } \lambda = 0
\end{cases}
\]</span></p>
<p>Here, <span class="math inline">\(\lambda\)</span> (lambda) is a parameter that determines the form and strength of the transformation. The logarithm (<span class="math inline">\(\ln y\)</span>) is a special case when <span class="math inline">\(\lambda = 0\)</span>.</p>
<p>So how do you decide what value to use for <span class="math inline">\(\lambda\)</span>? The algorithm to determine <span class="math inline">\(\lambda\)</span> is an iterative one that includes repeated fitting a linear model on transformed data and selecting the <span class="math inline">\(\lambda\)</span> with the maximum log-likelihood. Good news - R will do heavy repetitive lifting for you. Don’t just take R’s output and run with it though. You should always inspect diagnostic plots before and after applying Box-Cox to ensure it has improved model assumptions.</p>
<p><a href="#fig-cpubad" class="quarto-xref">Figure&nbsp;<span>5.5</span></a> shows residuals from our CPU performance model first seen in Chapter 4. When CPU performance is modeled as a linear function of estimated performance the variance of residuals is seen to grow substantially from left to right in our fitted vs.&nbsp;residual plot and a QQ plot of the residuals reveals notable deviations from Normality.</p>
<div id="fig-cpubad" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cpubad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cpubad" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-cpubad-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cpubad-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-cpubad-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-cpubad" width="259">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cpubad-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Fitted vs.&nbsp;Residuals
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cpubad" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-cpubad-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cpubad-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-cpubad-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-cpubad" width="259">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cpubad-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Residual QQ Plot
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cpubad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.5: CPU Performance Linear Model
</figcaption>
</figure>
</div>
<p>The plot shown in <a href="#fig-boxcox" class="quarto-xref">Figure&nbsp;<span>5.6</span></a> is produced when R is called on to evaluate values of <span class="math inline">\(\lambda\)</span> in a Box-Cox tranformation. Dotted lines are included to make reading off the ideal <span class="math inline">\(\lambda\)</span> easier. Details from R tell us the maximum log-likelihood occurs when <span class="math inline">\(\lambda =0.6262\)</span>.</p>
<div class="cell" data-layout-align="center" data-ech0="false">
<div class="cell-output-display">
<div id="fig-boxcox" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxcox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-boxcox-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" width="355">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxcox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.6: Box-Cox <span class="math inline">\(\lambda\)</span> log-likelihoods
</figcaption>
</figure>
</div>
</div>
</div>
<p>When the Box-Cox transformation with <span class="math inline">\(\lambda=.6262\)</span> is then applied to CPU performance something interesting happens though. Yes, the variance becomes much more stable, but we also see that there is significant curvature in the relationship between estimated CPU performance and our new transformed performance outcome. This necessitates a second step: transforming X, then re-running the Box Cox algorithm to find the optimal <span class="math inline">\(\lambda\)</span> when the transformed X is used to predict Y.</p>
<div id="fig-cpubc1" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cpubc1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cpubc1" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-cpubc1-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cpubc1-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-cpubc1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" data-ref-parent="fig-cpubc1" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cpubc1-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Plot of transformed data
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cpubc1" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-cpubc1-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cpubc1-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-cpubc1-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" data-ref-parent="fig-cpubc1" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cpubc1-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Add X Transformation
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cpubc1" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-cpubc1-3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cpubc1-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-cpubc1-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" data-ref-parent="fig-cpubc1" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cpubc1-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) New Box-Cox <span class="math inline">\(\lambda\)</span> plot
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cpubc1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.7: CPU Model with Box-Cox
</figcaption>
</figure>
</div>
<p>The curvature after the first Box-Cox round is shown in <a href="#fig-cpubc1" class="quarto-xref">Figure&nbsp;<span>5.7</span></a> (a), with the fitted line overlaid in blue to make clear just how much curvature is present. <a href="#fig-cpubc1" class="quarto-xref">Figure&nbsp;<span>5.7</span></a> (b) shows that if the square-root of estimated CPU performance is used instead of the estimated CPU performance directly the relationship becomes much more linear. Part (c) then shows the updated <span class="math inline">\(\lambda\)</span> estimate is slightly smaller at 0.4242.</p>
<p>The revised model model for CPU performance is now shown in <a href="#fig-cpubc2" class="quarto-xref">Figure&nbsp;<span>5.8</span></a>. The curvature is much improved, the variance appears fairly constant across the fitted vs.&nbsp;residual plot, and the QQ plot of residuals is much improved over the original QQ plot of <a href="#fig-cpubad" class="quarto-xref">Figure&nbsp;<span>5.5</span></a>.</p>
<div id="fig-cpubc2" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cpubc2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cpubc2" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-cpubc2-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cpubc2-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-cpubc2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-cpubc2" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cpubc2-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Plot of transformed data
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cpubc2" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-cpubc2-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cpubc2-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-cpubc2-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-cpubc2" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cpubc2-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Fitted vs.&nbsp;Residuals
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cpubc2" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-cpubc2-3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cpubc2-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-cpubc2-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-cpubc2" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cpubc2-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) QQ Plot
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cpubc2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.8: Updated CPU Box-Cox, sqrt(x)
</figcaption>
</figure>
</div>
<p>Work determining a model for CPU performance could certainly end here. <a href="#fig-cpubc2" class="quarto-xref">Figure&nbsp;<span>5.8</span></a> looks quite reasonable. However, there is still slight curvature in our data shown in plot (a). Maybe we then try a log(estperf) approach to handle curvature. Then a new Box Cox <span class="math inline">\(\lambda\)</span> search would be needed.</p>
<p><a href="#fig-cpubc3" class="quarto-xref">Figure&nbsp;<span>5.9</span></a> shows the result of using log(estperf) to predict a Box Cox with <span class="math inline">\(\lambda=0.10101\)</span> applied to CPU performance. The curvature issue is improved over what was seen in <a href="#fig-cpubc2" class="quarto-xref">Figure&nbsp;<span>5.8</span></a> (a), but the variance in <a href="#fig-cpubc3" class="quarto-xref">Figure&nbsp;<span>5.9</span></a> (b) is not nearly as consistent as in <a href="#fig-cpubc2" class="quarto-xref">Figure&nbsp;<span>5.8</span></a> (b) and creates homoskedasticity concerns. Normality is reasonably met with both models</p>
<div id="fig-cpubc3" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cpubc3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cpubc3" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-cpubc3-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cpubc3-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-cpubc3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-cpubc3" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cpubc3-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Plot of transformed data
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cpubc3" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-cpubc3-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cpubc3-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-cpubc3-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-cpubc3" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cpubc3-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Fitted vs.&nbsp;Residuals
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cpubc3" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-cpubc3-3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cpubc3-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-cpubc3-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-cpubc3" width="288">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cpubc3-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) QQ Plot
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cpubc3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.9: Updated CPU Box-Cox, log(x)
</figcaption>
</figure>
</div>
<p>So which model is the right model? Box-Cox combined with square-root of estimated performance, or Box-Cox combined with log estimated performance? I prefer the square-root one, but really this is where you have to accept something not all students handle well. There is no <u>one</u> right model. As you gain experience with regression and other data science techniques you will learn this work has an element of art to it. Two different statisticians will quite reasonably come up with two slightly different models and that doesn’t mean either one is wrong.</p>
<p>Statistician George Box (yup, the Box in Box-Cox) is credited with saying “All models are wrong, but some are useful.” He’s also credited with admonishing that “Statisticians, like artists, have a bad habit of falling in love with their models.” Take these words to heart. If two competing models seem equally useful, pick one and move on with your life. But also, if you discover a flaw in your model, don’t be so wedded to it that you don’t revise it to fix the flaw.</p>
<section id="in-r-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r-1">In R</h3>
<p>To work with Box-Cox transformations you’ll want to load the <code>MASS</code> library. From there it is as simple as using the <code>boxcox</code> function. The only input the function needs is your basic fitted model object, and it will then output the graph below.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>simple_mod<span class="ot">&lt;-</span><span class="fu">lm</span>(perf<span class="sc">~</span>estperf, <span class="at">data=</span>cpus)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>bc<span class="ot">&lt;-</span><span class="fu">boxcox</span>(simple_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chapter5_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="432"></p>
</figure>
</div>
</div>
</div>
<p>By saving the <code>boxcox</code> result as <code>bc</code> (or whatever other name you’d like) you are able to pull the optimal <span class="math inline">\(\lambda\)</span> parameter by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>bc<span class="sc">$</span>x[<span class="fu">which.max</span>(bc<span class="sc">$</span>y)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6262626</code></pre>
</div>
</div>
<p>And then apply the result:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bc_perf<span class="ot">&lt;-</span>((cpus<span class="sc">$</span>perf<span class="sc">^</span><span class="fl">0.6262626</span>)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">/</span><span class="fl">0.6262626</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>mod_bc<span class="ot">&lt;-</span><span class="fu">lm</span>(bc_perf<span class="sc">~</span>estperf, <span class="at">data=</span>cpus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="unit-change" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="unit-change"><span class="header-section-number">5.4</span> Unit change</h2>
<p>There is one last transformation to be aware of and it’s the simplest of all: a change of units. Regardless of the units used to measure <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> should remain unchanged. This means if our car fuel efficiency data had km per liter instead of miles per gallon, heavier cars would still be less efficient than lighter cars. It also means if we measured boiling point in degrees Celsius instead of Fahrenheit, the relationship between barometric pressure and boiling point should be the same as we saw back in <a href="#fig-bplog" class="quarto-xref">Figure&nbsp;<span>5.3</span></a> (a).</p>
<p>This doesn’t mean the fitted parameters stay the same as units change though. Consider our beer consumption model from <a href="Chapter2.html#sec-lsr" class="quarto-xref"><span>Section 2.3</span></a>. The data is recorded as cans of beer, but could just as easily have been measured in fluid ounces (and that probably would have been better for clarity). Let’s see how the model changes for the two measures of beer consumption:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">lm</span>(bac<span class="sc">~</span>beers, <span class="at">data=</span>bac)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) -0.01270060 0.012637502 -1.004993 3.319551e-01
beers        0.01796376 0.002401703  7.479592 2.969480e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>beer_oz<span class="ot">&lt;-</span>bac<span class="sc">$</span>beers<span class="sc">*</span><span class="dv">12</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>mod2<span class="ot">&lt;-</span><span class="fu">lm</span>(bac<span class="sc">~</span>beer_oz, <span class="at">data=</span>bac)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) -0.01270060 0.012637502 -1.004993 3.319551e-01
beer_oz      0.00149698 0.000200142  7.479592 2.969480e-06</code></pre>
</div>
</div>
<p>The intercepts of the two models are exactly the same, but the slopes are different. When beer is measure in cans, the slope is 0.01796 but when measured in fluid ounces, 12 times the can count, the slope is 0.0015. Notice that 12 times 0.0015 equals 0.01796. This makes sense because if <span class="math inline">\(bac=-0.0127+0.01796\times cans\)</span> then the relationship can be equivalently expressed as <span class="math inline">\(bac=-0.0127+(0.01796/12)\times(cans\times12)\)</span> (the 12s cancel out to make it all simply equal to multiplying by 1).</p>
<p>Standard error for our slope estimate changes by the same multiplier so in the end the t-value and corresponding p-value for slope remain unchanged.</p>
<p>Remember this simple transformation should you find yourself with really tiny slopes you’d like to make bigger, or really large slopes you’d like to make smaller, just for ease of communication. A quick change of measuring in kg to measuring in g will shrink a slope by a factor of 1000 just as going from m to km will increase it by a factor of 1000. Likewise sometimes it makes sense to use measure of 1,000s of people or millions of dollars just because the coefficients are unwieldy when individual people or dollars are the units. Talking about an increase of 2.3 extra points on statewide tests per million dollars in education spending is just easier than an increase of 0.0000023 points per dollar spent.</p>
</section>
<section id="on-your-own-all-transformations" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="on-your-own-all-transformations">On Your Own, All Transformations</h2>
<ol type="1">
<li><p>The <code>Puromycin</code> dataset in the <code>datasets</code> package contains information regarding an experiment investigating instantaneous enzymatic reaction rates of cells as a function of substrate concentrations.</p>
<ol type="a">
<li>Build a model for reaction rate as a function of concentration considering only those cells that are untreated. Communicate your model fit and provide evidence major assumptions on residuals are all met.</li>
<li>Build a model for reaction rate as a function of concentration considering only those cells that are treated. Communicate your model fit and provide evidence major assumptions on residuals are all met.</li>
<li>Create and explain a 90% prediction interval for the reaction rate of an untreated cell with a concentration of 0.4.</li>
<li>Create and explain a 90% confidence interval for the mean reaction rate of treated cells with a concentration of 0.4.</li>
<li>Is there sufficient evidence, at the <span class="math inline">\(\alpha=0.05\)</span> level, that the reaction rate change associated with changes in concentration is significantly different for the treated and untreated cell groups? Explain.</li>
</ol></li>
<li><p>The muscle dataset in the MASS library has information on an experiment on rat heart muscle. Using the data, fit a model predicting the change in muscle strip length using the calcium chloride solution concentration.</p>
<ol type="a">
<li><p>Explain what transformation you used and interpret your model. Show all assumptions are met.</p></li>
<li><p>Create a graph of your model, adding the fitted the curve to a plot of un-transformed concentration and length.</p></li>
<li><p>Is the expected length change with zero calcium chloride concentration greater than 0? Explain.</p></li>
</ol></li>
<li><p>The <code>mammals</code> dataset in the <code>MASS</code> library contains the brain and body weights of 62 mammals.</p>
<ol type="a">
<li><p>Apply the appropriate transformation to make a linear model work for predicting brain weight as a function of body weight. Explain your model and demonstrate all assumptions are met.</p></li>
<li><p>An adult llama weighs approximately 180kg. Create and explain a 90% prediction interval for the weight of a llama brain. After you’ve created your interval, google it and see if your interval contains the answer you find.</p></li>
<li><p>Create and interpret a 95% confidence interval for the slope of your model.</p></li>
</ol></li>
<li><p>Using the <code>pressure</code> dataset in the <code>datasets</code> package, fit an appropriate model for vapor pressure as a function of temperature.</p>
<ol type="a">
<li><p>Fitting the model requires a transformation. What transformation did you select and why?</p></li>
<li><p>What is the equation of your fitted line? Explain how pressure changes for every one degree increase in temperature.</p></li>
<li><p>Provide graphical evidence that all key assumptions are met in your model.</p></li>
<li><p>Modify the data to use temperature in degrees Farhenheit. How does your model change? Does this match your expectation? Explain.</p></li>
</ol></li>
<li><p>Using the <code>trees</code> dataset from the <code>datasets</code> package,</p>
<ol type="a">
<li><p>Fit a model for tree volume as a function of tree height. Discuss your chosen model and demonstrate assumptions are all met.</p></li>
<li><p>Fit a model for tree volume as a function of tree girth. Discuss your chosen model and demonstrate assumptions are all met.</p></li>
<li><p>Which model does a better job of predicting tree volume? Explain your choice.</p></li>
</ol></li>
<li><p>Use the <code>cabbages</code> data in the <code>MASS</code> library. Your goal is to fit a model for the weight of a head of cabbage as a function of the vitamin C content.</p>
<ol type="a">
<li><p>What assumption or assumptions are not met by a basic linear model? Explain how you know.</p></li>
<li><p>Apply a transformation and fit your model. Interpret the fit and give evidence assumptions are all met.</p></li>
</ol></li>
</ol>
</section>
<section id="weighted-least-squares" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="weighted-least-squares"><span class="header-section-number">5.5</span> Weighted Least Squares</h2>
<p>Sometimes your data points should not all be treated equally. Why not? Well consider the <code>babies_crawl</code> data frame in the <code>openintro</code> library. This data provides the average age at which babies began to crawl by birth month. Researchers speculated that babies who are bundled up for cold weather when they are six months old likely learn to crawl later than babies who are six months in warmer seasons and have less clothing inhibiting movement <span class="citation" data-cites="benson1993">(<a href="#ref-benson1993" role="doc-biblioref">Benson 1993</a>)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-babies" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-babies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-babies-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="336">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-babies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.10: Crawling Age and Temperature
</figcaption>
</figure>
</div>
</div>
</div>
<p>From <a href="#fig-babies" class="quarto-xref">Figure&nbsp;<span>5.10</span></a> it looks like the hypothesis has some merit. A best fit line would reach from the upper left to the lower right indicating babies with warmer temperatures are crawling earlier than babies learning in colder temperatures. However, this plot is hiding some key information about the data. We have just one point for every birth month, but each birth month includes anywhere from 21 to 49 babies. Some months the standard deviation of crawling age was less than 6 weeks, but others it was greater than 8 weeks. If we treat each point equally, those differences of samples sizes and in-month variability are lost.</p>
<p>Enter Weighted Least Squares (WLS) regression. By applying WLS, you give more weight to observations you trust more, and less weight to those you trust less. Generally in simple linear regression our goal is to fit the <span class="math inline">\(Y_i = \beta_0 + \beta_1 X_i + \epsilon_i\)</span> model to minimize <span class="math inline">\(\sum_{i=1}^{n} (Y_i - \hat{Y}_i)^2\)</span>, the sum of squared residuals. With WLS we instead aim to minimize weighted residuals <span class="math inline">\(\sum_{i=1}^{n} w_i (Y_i - \hat{Y}_i)^2\)</span> where, <span class="math inline">\(w_i\)</span> is the weight assigned to the <span class="math inline">\(i^{th}\)</span> data point. Along with this, our SST and SSR change to incorporate weights as well:</p>
<p><span class="math display">\[
SSError=SSE=\sum w_i(y_i-\hat{y}_i)^2
\]</span></p>
<p><span class="math display">\[
SSTotal=SST=\sum w_i(y_i-\bar{y})^2
\]</span></p>
<p><span class="math display">\[
SSRegression=SSR=\sum w_i(\bar{y}_i-\hat{y}_i)^2
\]</span></p>
<p>It still holds that SST=SSE+SSR. Comparing <span class="math inline">\(R^2\)</span> values of models with different weights is not a fair comparison when evaluation options. Choosing suitable and appropriate weights is crucial. Common approaches include:</p>
<ul>
<li><p><strong>Inverse Variance Weighting (Most Common)</strong></p>
<p>If each observation has a known variance <span class="math inline">\(\sigma_i^2\)</span> , assign <span class="math inline">\(w_i=1/\sigma_i^2\)</span>. This means observations with smaller variance (higher precision) get more weight.</p></li>
<li><p><strong>Based on Measurement Error</strong></p>
<p>If the measurement error for each <span class="math inline">\(Y_i\)</span> is known, assign smaller weight to points with larger error.</p></li>
<li><p><strong>Subjective or Utility Weights</strong></p>
<p>Sometimes weights reflect how important or relevant each data point is for your particular context.</p></li>
<li><p><strong>Iteratively Estimated Weights</strong></p>
<p>When heteroskedasticity is present but true variances are unknown, estimate the relationship between variance and the predictor and then assign weights accordingly.</p></li>
</ul>
<p>By understanding when and how to assign weights, you can improve the performance of your regression analysis and draw better conclusions from your data.</p>
<p>In the <code>babies_crawl</code> data, the number of babies for each month is given in the <code>n</code> column, and the standard deviation of crawling age observed within each month is given in <code>sd</code>. From the Central Limit Theorem, we know these two components can give us the standard error for the 12 average crawling ages: <span class="math inline">\(\frac{sd}{sqrt(n)}\)</span>. Using the inverse of standard error as weights will give higher weights to low standard errors and low weights to months with high standard errors.</p>
<p><a href="#fig-babies2" class="quarto-xref">Figure&nbsp;<span>5.11</span></a> shows the model without weights in a red dashed line, and the model using weights in blue. Each point in the plot is sized relative to it’s weight so we can see the unusually low crawling age at a temperature of 52 is weighted quite low in the weighted model.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-babies2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-babies2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-babies2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" width="316">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-babies2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.11: Crawling Age and Temperature, two models
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now for an example that doesn’t have standard deviation provided directly. In the <code>openintro</code> library you’ll find the <code>mammals</code> data frame that contains not only brain and body weight as we looked at earlier, but also information on sleep and dreaming.</p>
<div id="fig-mamsleep" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mamsleep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mamsleep" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-mamsleep-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mamsleep-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-mamsleep-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-mamsleep" width="336">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mamsleep-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Data with fitted line
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mamsleep" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-mamsleep-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mamsleep-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-mamsleep-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-mamsleep" width="336">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mamsleep-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Fitted vs.&nbsp;Residuals
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mamsleep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.12: Mammal Sleeping and Non-Dreaming
</figcaption>
</figure>
</div>
<p>If you split the data into four quartiles and calculate the variance for each group the result is as shown in <a href="#fig-mamsleepvar" class="quarto-xref">Figure&nbsp;<span>5.13</span></a> (a). Though close, the relationship between the center of each grouping and the group’s residual variance is not quite linear but a simple square transformation on the group center fixes that. This means the variance of the residuals can be modeled linearly by the square of X. Therefore, to use inverse variance as our weights then, we can use <span class="math inline">\(\frac{1}{X^2}\)</span>.</p>
<div id="fig-mamsleepvar" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mamsleepvar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mamsleepvar" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-mamsleepvar-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mamsleepvar-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-mamsleepvar-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-mamsleepvar" width="326">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mamsleepvar-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Four group variances
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mamsleepvar" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-mamsleepvar-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mamsleepvar-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-mamsleepvar-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-ref-parent="fig-mamsleepvar" width="326">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mamsleepvar-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Group centers squared vs group variances
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mamsleepvar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.13: Mammal Sleeping and Non-Dreaming
</figcaption>
</figure>
</div>
<p>Without incorporating weights, the model is the dashed orchid line shown in <a href="#fig-mamsleepwt" class="quarto-xref">Figure&nbsp;<span>5.14</span></a>. With the inverse <span class="math inline">\(X^2\)</span> weights the model is the solid blue line. The models are quite close, but real differences emerge when inference methods are applied under the two models. That is because <span class="math inline">\(S_R\)</span> now includes the weights:</p>
<p><span class="math display">\[
S_{R,w}=\sqrt\frac{\sum w_i(y_i-\hat{y_i})^2}{n-2}
\]</span></p>
<p>and weights further play a role in the standard errors for the weighted model coefficients as:</p>
<p><span class="math display">\[
SE_{\hat{β}_{0,w}}=S_{R,w}\sqrt{\frac{1}{n}+\frac{\bar{x}_w^2}{\sum w_i(x-\bar{x})^2}}
\]</span></p>
<p><span class="math display">\[
SE_{\hat{β}_{1,w}}=\frac{S_{R,w}}{\sqrt{\sum w_i(x-\bar{x}_w)^2}}
\]</span></p>
<p>where <span class="math inline">\(\bar{x}_w\)</span> is the weighted mean: <span class="math display">\[\bar{x}_w=\frac{\sum(w_i \times x_i)}{\sum{w_i}}\]</span></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mamsleepwt" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mamsleepwt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter5_files/figure-html/fig-mamsleepwt-1.png" class="img-fluid figure-img" width="384">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mamsleepwt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.14: Mammal sleep model, Weighted &amp; Unweighted
</figcaption>
</figure>
</div>
</div>
</div>
<p>This means in the unweighted model, <span class="math inline">\(S_R=\)</span> 1.0026 but in the weighted version, <span class="math inline">\(S_R=\)</span> 0.0902.</p>
<p>Further, for the unweighted model the 95% confidence interval for slope <span class="math inline">\(\hat \beta_1\)</span> ranges from 0.7064 up to 0.8349 but in the weighted model the interval for <span class="math inline">\(\hat{\beta}_{1,w}\)</span>is from 0.7717 to 0.8796.</p>
<p>Similarly, inference for Y values corresponding to a particular <span class="math inline">\(X=x_*\)</span> changes with revised standard error equations:</p>
<p><span class="math display">\[
SE_{\bar{Y}|x_*,w}=S_{R,w}\sqrt{\frac{1}{\sum w_i}+\frac{(x_*-\bar{x}_w)^2}{\sum{(x_i-\bar{x}_w)^2}}}
\]</span></p>
<p>The standard error of the next Y at a given X takes on this form:</p>
<p><span class="math display">\[
SE_{y|x_*,w}=S_{R,w}\sqrt{\frac{1}{w_*}+ \frac{1}{\sum w_i}+\frac{(x_*-\bar{x}_w)^2}{\sum{w_i(x_i-\bar{x}_w)^2}}}
\]</span></p>
<p>where <span class="math inline">\(w_*\)</span> is the weight associated with <span class="math inline">\(x_*\)</span>, the X location of the prediction.</p>
<p>This means that while the 95% prediction interval for the amount of non-dreaming sleep that is typical for a mammal that gets nine hours total sleep ranges from 5.32 to 9.4 with the unweighted model, our weighted model produces a narrower interval going from 5.68 to 8.98.</p>
<section id="in-r-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r-2">In R</h3>
<p>The <code>lm</code> command accommodates weights with minimal change to the code you’ve already learned:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mod_mam_sleep_wt<span class="ot">&lt;-</span><span class="fu">lm</span>(non_dreaming<span class="sc">~</span>total_sleep, <span class="at">data=</span>mammals, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">weights=</span><span class="dv">1</span><span class="sc">/</span>mammals<span class="sc">$</span>total_sleep<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_mam_sleep_wt)<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error    t value     Pr(&gt;|t|)
(Intercept) -0.1039658 0.20031687 -0.5190066 6.062443e-01
total_sleep  0.8256810 0.02681064 30.7967632 2.383219e-32</code></pre>
</div>
</div>
<p>The <code>confint</code> and <code>predict.lm</code> functions can still be used on weighted models just as you did with the simpler models without weights. With prediction intervals, you’ll need to input the weight that should be used at the <span class="math inline">\(X=x_*\)</span> of interest.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod_mam_sleep_wt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept) -0.5071827 0.2992512
total_sleep  0.7717140 0.8796480</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict.lm</span>(mod_mam_sleep_wt, <span class="fu">data.frame</span>(<span class="at">total_sleep=</span><span class="fu">c</span>(<span class="dv">9</span>,<span class="dv">12</span>)), </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">interval=</span><span class="st">"prediction"</span>, <span class="at">weights=</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">81</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">144</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr       upr
1 7.327163 5.675607  8.978719
2 9.804206 7.596301 12.012112</code></pre>
</div>
</div>
</section>
<section id="on-your-own" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="on-your-own">On Your Own</h3>
<ol type="1">
<li><p>Install and load the <code>fivethirtyeight</code> package. Using the <code>murder_2015_final</code> data file, estimate the 2015 murder rate in large US cities using the 2014 murder rates.</p>
<ol type="a">
<li><p>Begin by fitting a basic model in the form of murders_2015~murders_2014 regression model. Check all inference assumptions. Which assumptions are met and which need attention?</p></li>
<li><p>Develop a model for the variance to be used in a weighted model. Explain your approach.</p></li>
<li><p>Fit and interpret your weighted least squares model.</p></li>
</ol></li>
<li><p>Examine the Rabbit data frame in the MASS library.</p>
<ol type="a">
<li><p>Find the variance for each dose level and use that in a weighted regression model predicting blood pressure change. Explain what your model shows.</p></li>
<li><p>Complete and interpret a 95% confidence interval for the mean change in blood pressure when given a dose of 80 micrograms of Phenylbiguanide.</p></li>
</ol></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-benson1993" class="csl-entry" role="listitem">
Benson, Janette B. 1993. <span>“Season of Birth and Onset of Locomotion: Theoretical and Methodological Implications.”</span> <em>Infant Behavior and Development</em> 16 (1): 69–81. <a href="https://doi.org/10.1016/0163-6383(93)80029-8">https://doi.org/10.1016/0163-6383(93)80029-8</a>.
</div>
<div id="ref-Geiman2023" class="csl-entry" role="listitem">
Geiman, Claire, and Eric Long. 2023. <span>“Data from: Allometric Brain Reduction in an Insular, Dwarfed Population of Black-Tailed Deer.”</span> Dryad. <a href="https://doi.org/10.5061/DRYAD.GQNK98STM">https://doi.org/10.5061/DRYAD.GQNK98STM</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Chapter4.html" class="pagination-link" aria-label="Assumptions Were Made">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Assumptions Were Made</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Chapter6.html" class="pagination-link" aria-label="Zeros and Ones">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Zeros and Ones</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>