<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; How sure are you? – Intro Regression In R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Chapter4.html" rel="next">
<link href="./Chapter2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0615981f0f11b1670b07f78b9ae6e573.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Chapter3.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">How sure are you?</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Intro Regression In R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualize the Relationship</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Add a Line</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">How sure are you?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Assumptions Were Made</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Make it Work</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Zeros and Ones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Go Bigger</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Building and Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Well that’s weird</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#inference-for-model-coefficients" id="toc-inference-for-model-coefficients" class="nav-link active" data-scroll-target="#inference-for-model-coefficients"><span class="header-section-number">3.1</span> Inference for Model Coefficients</a>
  <ul class="collapse">
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"><span class="header-section-number">3.1.1</span> Confidence Intervals</a></li>
  <li><a href="#hypothesis-tests" id="toc-hypothesis-tests" class="nav-link" data-scroll-target="#hypothesis-tests"><span class="header-section-number">3.1.2</span> Hypothesis tests</a></li>
  <li><a href="#Rcode" id="toc-Rcode" class="nav-link" data-scroll-target="#Rcode">In R</a></li>
  <li><a href="#Exercises" id="toc-Exercises" class="nav-link" data-scroll-target="#Exercises">On Your Own</a></li>
  </ul></li>
  <li><a href="#confidence-intervals-for-baryx" id="toc-confidence-intervals-for-baryx" class="nav-link" data-scroll-target="#confidence-intervals-for-baryx"><span class="header-section-number">3.2</span> Confidence Intervals for <span class="math inline">\(\bar{Y}|X\)</span></a>
  <ul class="collapse">
  <li><a href="#in-r" id="toc-in-r" class="nav-link" data-scroll-target="#in-r">In R</a></li>
  <li><a href="#on-your-own" id="toc-on-your-own" class="nav-link" data-scroll-target="#on-your-own">On Your Own</a></li>
  </ul></li>
  <li><a href="#prediction-intervals-for-y" id="toc-prediction-intervals-for-y" class="nav-link" data-scroll-target="#prediction-intervals-for-y"><span class="header-section-number">3.3</span> Prediction Intervals for <span class="math inline">\(Y\)</span></a>
  <ul class="collapse">
  <li><a href="#in-r-1" id="toc-in-r-1" class="nav-link" data-scroll-target="#in-r-1">In R</a></li>
  <li><a href="#on-your-own-1" id="toc-on-your-own-1" class="nav-link" data-scroll-target="#on-your-own-1">On Your Own</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">How sure are you?</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Every confidence interval you learned in intro statistics has the same basic format:<span class="math display">\[
point\: estimate \pm multiplier\times standard \: error
\]</span> Similarly, the hypothesis tests you’ve learned for means and proportions have test statistics in the general format of:</p>
<p><span class="math display">\[
\frac{observed \: value - hypothesized\: value}{standard\: error}
\]</span></p>
<p>Both of these basic structures will continue in the realm of regression analysis.</p>
<section id="inference-for-model-coefficients" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="inference-for-model-coefficients"><span class="header-section-number">3.1</span> Inference for Model Coefficients</h2>
<p>You can now fit a regression model, but in many ways that’s equivalent to being able to calculate a sample mean. The least-squares fit gives you a way to describe your sample data well, but the line alone doesn’t tell you all you need to make statements about the population your sample came from. Just as you learned how to put a confidence interval on a sample mean in intro stat, you’ll now put confidence intervals on your fitted model coefficients. Confidence intervals allow you to quantify how much uncertainty surrounds the estimates of the intercept <span class="math inline">\((β_0)\)</span> and slope <span class="math inline">\((β_1)\)</span> coefficients.</p>
<p>Consider the <code>cats</code> data frame available in the <code>MASS</code> library for R. This data frame includes the body weight (in kg) and heart weight (in grams) for 144 cats. The least-squares fit for the first 50 cats in <a href="#fig-catmod" class="quarto-xref">Figure&nbsp;<span>3.1</span></a>.</p>
<p>But what if a different sample of 50 cats had been selected? How different might the <span class="math inline">\(\hat{β_0}\)</span> and <span class="math inline">\(\hat{β_1}\)</span> be? <a href="#fig-catmod" class="quarto-xref">Figure&nbsp;<span>3.1</span></a> (b) shows five different regression lines fit on five different samples of size 50 from the cat data superimposed on a scatterplot of all 144 cats in the data frame.</p>
<div id="fig-catmod" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-catmod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-catmod" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-catmod-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-catmod-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter3_files/figure-html/fig-catmod-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" data-ref-parent="fig-catmod" width="384">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-catmod-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Fit of first 50 cats
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-catmod" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-catmod-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-catmod-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Chapter3_files/figure-html/fig-catmod-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" data-ref-parent="fig-catmod" width="384">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-catmod-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) 5 fits from 5 samples of 50
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catmod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1: Cat Body and Heart Weight
</figcaption>
</figure>
</div>
<p>As you see, each sample produces a slightly different line. The five intercepts range from -2.164 up to 1.141, and the five slopes range from 3.4268 up to 4.8005. Clearly which random sample you look at matters, and when this variability exists we need a confidence intervals to communicate this uncertainty, and hypothesis testing is needed to evaluate hypotheses.</p>
<section id="confidence-intervals" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="confidence-intervals"><span class="header-section-number">3.1.1</span> Confidence Intervals</h3>
<section id="intercept-β_0" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="intercept-β_0"><em>Intercept</em> <span class="math inline">\(β_0\)</span></h4>
<ul>
<li><p>The point estimate for the intercept in your linear model describing the relationship between X and Y is simply your <span class="math inline">\(\hat{β_0}\)</span>.</p></li>
<li><p>The multiplier used in your confidence interval will come from a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom. Why <span class="math inline">\(n-2\)</span>? You started with n data points (and n degrees of freedom), and then you lose one degree of freedom for each parameter you estimate. You estimated two parameters: <span class="math inline">\(β_0\)</span> and <span class="math inline">\(β_1\)</span>, hence <span class="math inline">\(n-2\)</span>.</p></li>
<li><p>The standard error for <span class="math inline">\(\hat{β_0}\)</span> is <span class="math inline">\(SE_{\hat{β_0}}=S_R\sqrt{\frac{1}{n}+\frac{\bar{x}^2}{\sum(x-\bar{x})^2}}\)</span> where <span class="math inline">\(S_R=\sqrt\frac{\sum(y_i-\hat{y_i})^2}{n-2}\)</span>, the standard deviation of the residuals.</p></li>
</ul>
<div style="page-break-after: always;"></div>
<p><strong>Example with cat heart weight model from <a href="#fig-catmod" class="quarto-xref">Figure&nbsp;<span>3.1</span></a> (a)</strong></p>
<ul>
<li><p>Point estimate is simply <span class="math inline">\(\hat{β_0}=2.4368\)</span>.</p></li>
<li><p>With <span class="math inline">\(n=50\)</span> there are <span class="math inline">\(50-2=48\)</span> degrees of freedom, so for a 95% confidence interval the multiplier will be <span class="math inline">\(t_{.025, 48}=2.010635\)</span>.</p></li>
<li><p>Using the components <span class="math inline">\(\bar{x}=2.34\)</span>, <span class="math inline">\(\sum(x-\bar{x})^2=3.76\)</span>, and <span class="math inline">\(S_R=1.2007\)</span>, we can calculate <span class="math inline">\(SE_{\hat{β_0}}=1.2007 \sqrt{\frac{1}{50}+\frac{2.34^2}{3.76}}=1.4588\)</span>.</p></li>
<li><p>Interval: <span class="math inline">\(2.4368\pm(2.010635\times 1.4588)=(-0.4963, 5.3699)\)</span></p></li>
<li><p>With this, we are 95% confident that the interval going from <span class="math inline">\(-0.4963\)</span> to <span class="math inline">\(5.3699\)</span> captures the intercept for the linear model describing heart weight as a function of body weight in the full population of cats.</p></li>
</ul>
</section>
<section id="slope-β_1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="slope-β_1"><em>Slope</em> <span class="math inline">\(β_1\)</span></h4>
<ul>
<li><p>The point estimate for the intercept in your linear model describing the relationship between X and Y is simply your <span class="math inline">\(\hat{β_0}\)</span>.</p></li>
<li><p>The multiplier used in your confidence interval will come from a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom. Why <span class="math inline">\(n-2\)</span>? You started with n data points (and n degrees of freedom), and then you lose one degree of freedom for each parameter you estimate. You estimated two parameters: <span class="math inline">\(β_0\)</span> and <span class="math inline">\(β_1\)</span>, hence <span class="math inline">\(n-2\)</span>.</p></li>
<li><p>The standard error for <span class="math inline">\(\hat{β_1}\)</span> is <span class="math inline">\(SE_{\hat{β_1}}=\frac{S_R}{\sqrt{\sum(x-\bar{x})^2}}\)</span> with <span class="math inline">\(S_R\)</span> the same as before.</p></li>
</ul>
<p><strong>Example with cat heart weight model from <a href="#fig-catmod" class="quarto-xref">Figure&nbsp;<span>3.1</span></a> (a)</strong></p>
<ul>
<li><p>Point estimate is simply <span class="math inline">\(\hat{β_1}=2.8527\)</span>.</p></li>
<li><p>With <span class="math inline">\(n=50\)</span> there are <span class="math inline">\(50-2=48\)</span> degrees of freedom, so for a 95% confidence interval the multiplier will be <span class="math inline">\(t_{.025, 48}=2.010635\)</span>.</p></li>
<li><p>Using the components <span class="math inline">\(\sum(x-\bar{x})^2=3.76\)</span>, and <span class="math inline">\(S_R=1.2007\)</span>, we can calculate <span class="math inline">\(SE_{\hat{β_1}}=\frac{1.2007}{\sqrt{3.76}}=0.6192\)</span></p></li>
<li><p>Interval: <span class="math inline">\(2.8527\pm(2.010635\times 0.6192)=(1.6077, 4.0977)\)</span></p></li>
<li><p>With this, we are 95% confident that the interval going from <span class="math inline">\(1.6077\)</span> to <span class="math inline">\(4.0977\)</span> captures the slope for the linear model describing heart weight as a function of body weight in the full population of cats.</p></li>
</ul>
</section>
</section>
<section id="hypothesis-tests" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="hypothesis-tests"><span class="header-section-number">3.1.2</span> Hypothesis tests</h3>
<p>Hypothesis tests for regression coefficients most often test the null hypothesis that <span class="math inline">\(β_0=0\)</span> or that <span class="math inline">\(β_1=0\)</span>, but there is nothing stopping you from testing any value of interest for <span class="math inline">\(β_0\)</span> or <span class="math inline">\(β_1\)</span>.</p>
<section id="intercept-β_0-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="intercept-β_0-1"><em>Intercept</em> <span class="math inline">\(β_0\)</span></h4>
<p>To test <span class="math inline">\(H_0:β_0=b_0\)</span> the test statistic is <span class="math inline">\(t=\frac{\hat{β_0}-b_0}{SE_{β_0}}\)</span> with <span class="math inline">\(SE_{\hat{β_0}}\)</span> as defined earlier. The test statistic follows a t distribution with <span class="math inline">\(n-2\)</span> degrees of freedom.</p>
<p><strong>Example with cat heart weight model from <a href="#fig-catmod" class="quarto-xref">Figure&nbsp;<span>3.1</span></a> (a):</strong></p>
<ul>
<li><p><span class="math inline">\(H_0:β_0=0\)</span> corresponding to testing if the line passes through the origin.</p></li>
<li><p>Test statistic <span class="math inline">\(t=\frac{\hat{β_0}-0}{SE_{β_0}}=\frac{2.4368-0}{1.4588}=1.670\)</span>.</p></li>
<li><p>Being a two-tailed test, the p-value is the area under the <span class="math inline">\(t_{df=48}\)</span> distribution curve to the right of 1.670 and to the left of -1.670. This comes out to <span class="math inline">\(p=0.1014\)</span>, indicating there is not evidence the intercept differs from 0.</p></li>
</ul>
</section>
<section id="slope-β_1-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="slope-β_1-1"><em>Slope</em> <span class="math inline">\(β_1\)</span></h4>
<p>As with intercept, to test <span class="math inline">\(H_1:β_1=b_1\)</span> the test statistic is <span class="math inline">\(t=\frac{\hat{β_1}-b_1}{SE_{β_1}}\)</span> with <span class="math inline">\(SE_{\hat{β_1}}\)</span> as defined earlier and the test statistic follows a t distribution with <span class="math inline">\(n-2\)</span> degrees of freedom.</p>
<p><strong>Example with cat heart weight model from <a href="#fig-catmod" class="quarto-xref">Figure&nbsp;<span>3.1</span></a> (a):</strong></p>
<ul>
<li><p><span class="math inline">\(H_0:β_1=0\)</span> corresponding to testing if the line is horizontal meaning knowing a cat’s body weight gives no meaningful insight into it’s heart weight.</p></li>
<li><p>Test statistic <span class="math inline">\(t=\frac{\hat{β_1}-0}{SE_{β_1}}=\frac{2.8527-0}{0.6192}=4.607\)</span>.</p></li>
<li><p>Being a two-tailed test, the p-value is the area under the <span class="math inline">\(t_{df=48}\)</span> distribution curve to the right of 4.607 and to the left of -4.607. This comes out to <span class="math inline">\(p&lt;0.0001\)</span>, indicating there is strong evidence the slope differs from 0.</p></li>
</ul>
</section>
</section>
<section id="Rcode" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="Rcode">In R</h3>
<section id="confidence-intervals-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="confidence-intervals-1"><em>Confidence Intervals</em></h4>
<p>There are a couple ways you can get your confidence intervals using R. Option one is to use the summary command to get the various elements you need for the intervals:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>mod_cat<span class="ot">&lt;-</span><span class="fu">lm</span>(Hwt<span class="sc">~</span>Bwt, <span class="at">data=</span>cats[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>,])</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_cat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Hwt ~ Bwt, data = cats[1:50, ])

Residuals:
     Min       1Q   Median       3Q      Max 
-2.98316 -0.79264 -0.00526  0.86316  2.28737 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.4368     1.4588   1.670    0.101    
Bwt           2.8527     0.6192   4.607 3.03e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.201 on 48 degrees of freedom
Multiple R-squared:  0.3066,    Adjusted R-squared:  0.2922 
F-statistic: 21.23 on 1 and 48 DF,  p-value: 3.029e-05</code></pre>
</div>
</div>
<p>There is lots of great information in this summary output. It begins with the <em>Call</em> section that shows you the function call you made that created the model object in the first place. Next is the <em>Residuals</em> section that gives you the five number summary for the model residuals providing a snapshot of the model errors. The <em>Coefficients</em> section has the output you care about most. This table gives you the <span class="math inline">\(\hat{β_0}\)</span> and <span class="math inline">\(\hat{β_1}\)</span> estimates along with their standard errors. Highlighted below as an example is the detail for the intercept. The estimate for <span class="math inline">\(\hat{β_0}\)</span> of <span class="math inline">\(2.4368\)</span> is in the Estimate column, and the standard error of <span class="math inline">\(\hat{β_0}\)</span> , <span class="math inline">\(1.4588\)</span> appears along side it in the Std. Error column.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="summary coef table1.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Highlighted summary table" width="454"></p>
</figure>
</div>
<p>Getting your t multiplier then is as simple as using the qt function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(.<span class="dv">025</span>, <span class="at">df=</span><span class="dv">48</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.010635</code></pre>
</div>
</div>
<p>Also helpful: the “Residual standard error” given in the summary output below the <em>Coefficients</em> table is the <span class="math inline">\(S_R\)</span> used in the standard error formulas.</p>
<p>If you want to have R do even more of the work for you, there’s the <code>confint</code> function. This provides you confidence intervals on both the intercept and slope as easily as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod_cat, <span class="at">level=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %   97.5 %
(Intercept) -0.4963738 5.369927
Bwt          1.6076963 4.097623</code></pre>
</div>
</div>
</section>
<section id="hypothesis-tests-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="hypothesis-tests-1"><em>Hypothesis Tests</em></h4>
<p>The summary of your regression model Coefficients table not only gives the point estimate and standard error, but also the test statistic and p-value for the test of whether <span class="math inline">\(β_i=0\)</span>. Below is the cat model summary table highlighted to show the details for the test of <span class="math inline">\(β_1=0\)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="summary coef table2.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="summary table highlighted" width="454"></p>
</figure>
</div>
<p>The third column gives the t test statistic, <span class="math inline">\(4.607\)</span>, and the fourth column provides the p-value for the test. To the right of the p-value column R provides a code indicating the outcome of test. If the p-value is below 0.001 as is the case with slope here, three astrisk marks are shown. A p-value between 0.01 and 0.001 gets two asterisks, between 0.01 and 0.05, a single asterisk, a single “.” appears if the p-value is between 0.05 and 0.1, and the area is blank if the p-value is greater than 0.1. This is why no symbol is seen in the first row corresponding to the intercept.</p>
</section>
</section>
<section id="Exercises" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="Exercises">On Your Own</h3>
<ol type="1">
<li>Consider the <code>bac</code> data frame from the <code>openintro</code> library. Fit a regression model predicting blood alcohol content as a linear function of beer consumption.
<ol type="a">
<li>Interpret your model.</li>
<li>Complete and interpret a 95% confidence interval for the intercept.</li>
<li>Complete and interpret a 95% confidence interval for the slope. What does the intercept mean in the context of this data?</li>
<li>Is there significant evidence at the <span class="math inline">\(α=0.05\)</span> level that the intercept is different from zero?</li>
<li>Is there significant evidence at the <span class="math inline">\(α=0.05\)</span> level that the slope is greater than 0.015?</li>
</ol></li>
<li>Consider the <code>mtcars</code> data frame from the <code>datasets</code> library. Fit a linear regression model predicting mpg as a function of vehicle weight in 1,000s of lbs.
<ol type="a">
<li>Interpret your model.</li>
<li>Complete and interpret a 95% confidence interval for the intercept. What would the intercept mean in this context?</li>
<li>Complete and interpret a 95% confidence interval for the slope.</li>
<li>Is there significant evidence at the <span class="math inline">\(α=0.05\)</span> level that a car’s fuel efficiency drops by an average of more than 5 mpg for every extra 1,000 lbs weight?</li>
</ol></li>
<li>Consider the record race times for Scottish hill races provided in the <code>hills</code> data in the <code>MASS</code> library. Fit a linear model predicting the record race time in minutes as a function of the race distance length in miles.
<ol type="a">
<li>Interpret your model.</li>
<li>What does the intercept mean in this context? Complete and interpret a 90% confidence interval for intercept.</li>
<li>Complete and interpret a 90% confidence interval for the slope.</li>
<li>Is there significant evidence at the <span class="math inline">\(α=0.01\)</span> level that an additional mile of race distances increases the record winning time by more than 7 minutes?</li>
</ol></li>
<li>Consider our <code>cats</code> heart and body weight data from the <code>MASS</code> library.
<ol type="a">
<li>Fit a model predicting cat heart weight as a function of body weight using only the Male cats. Interpret your result.</li>
<li>Fit a model predicting cat heart weight as a function of body weight using only the Female cats. Interpret your result.</li>
<li>Complete 90% confidence intervals for the slopes of each model. Discuss your results. Is there evidence the relationship between heart weight and body weight varies by cat sex?</li>
</ol></li>
</ol>
</section>
</section>
<section id="confidence-intervals-for-baryx" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="confidence-intervals-for-baryx"><span class="header-section-number">3.2</span> Confidence Intervals for <span class="math inline">\(\bar{Y}|X\)</span></h2>
<p>In addition to confidence intervals for regression coefficients, you can also create confidence intervals for the mean Y at a given value of X. The point estimate that serves as the center of your confidence interval is simply the predicted value of Y given X based on your model fit and the multiplier is again a t distribution multiplier with <span class="math inline">\(n-2\)</span> degrees of freedom.</p>
<p>The standard error of <span class="math inline">\(\bar{Y}\)</span> when <span class="math inline">\(X=x_*\)</span> is</p>
<p><span class="math display">\[
SE_{\bar{Y}|x_*}=S_R\sqrt{\frac{1}{n}+\frac{(x_*-\bar{x})^2}{\sum{(x_i-\bar{x})^2}}}
\]</span></p>
<p>The <span class="math inline">\(S_R\)</span> is the same one seen in section 3.1 and reflects the variability of residual error observed with the model fit. The <span class="math inline">\((x_*-\bar{x})^2\)</span> component is entirely new though. If you look back at Figure 2, you’ll see the five lines are closest together near the center of our collection of X values. On the outer edges, the lines are farther apart. This means we are much more confident in our prediction of Y given X in the middle of the X range than we are on the edges of the observed X range. That is what the <span class="math inline">\((x_*-\bar{x})^2\)</span> component is capturing because <span class="math inline">\(x_*\)</span> is the value of X for which you are predicting Y. When <span class="math inline">\(x_*\)</span> is close to <span class="math inline">\(\bar{x}\)</span>, this term will quite small and only the <span class="math inline">\(\frac{1}{n}\)</span> in the square-root will really matter. When <span class="math inline">\(x_*\)</span> is far from <span class="math inline">\(\bar{x}\)</span>, this term will be large and the full <span class="math inline">\(SE_{(\bar{Y}|X)}\)</span> will increase.</p>
<p>So using our cat body and heart weight data model on the first 50 cats, if we are interested in the mean heart weight of cats with a body weight of 2.3 lbs, the steps to complete a 98% confidence interval would look like:</p>
<p><span class="math display">\[
\hat{Y}|(X=2.3)\pm t_{\frac{0.02}{2}, 48}\times SE_{(\bar{Y}|X=2.3)}
\]</span></p>
<p><span class="math display">\[
\hat{β_0}+(\hat{β_1}\times2.3)\pm 2.4066 \times 1.2007\sqrt {\frac{1}{50}+\frac{(2.3-2.34)^2}{3.76}}
\]</span></p>
<p><span class="math display">\[
8.9979\pm2.4066\times0.1716
\]</span></p>
<p><span class="math display">\[
(8.5849, 9.4109)
\]</span></p>
<p>The interval for the mean heart weight of cats with a weight of 2.9 lbs however would be:</p>
<p><span class="math display">\[
\hat{β_0}+(\hat{β_1}\times2.9)\pm 2.4066 \times 1.2007\sqrt {\frac{1}{50}+\frac{(2.9-2.34)^2}{3.76}}
\]</span></p>
<p><span class="math display">\[
10.7095\pm2.4066\times0.3861
\]</span></p>
<p><span class="math display">\[
(9.7803, 11.6387)
\]</span></p>
<p>Because 2.9 lbs is farther from the mean X of 2.34, the <span class="math inline">\(SE_{\bar{Y}|X=2.9}&gt;SE_{\bar{Y}|X=2.3}\)</span> resulting in a wider interval.</p>
<section id="in-r" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r">In R</h3>
<p>Confidence intervals for <span class="math inline">\(\bar{Y}|X=x_*\)</span> are available through the same predict.lm function seen in Chapter 2 for calculating predicted values with your model. The usage begins the same as with finding predicted values: you input your fitted model object and then a data frame with the <span class="math inline">\(x_*\)</span> values of interest. All that’s needed beyond that is specifying <code>interval="confidence"</code>. By default the confidence level is .95, but any value can be specified with a <code>level=</code> input as shown in the example below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mod_cat<span class="ot">&lt;-</span><span class="fu">lm</span>(Hwt<span class="sc">~</span>Bwt, <span class="at">data=</span>cats[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>,])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>new_cats<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">Bwt=</span><span class="fu">c</span>(<span class="fl">2.3</span>, <span class="fl">2.9</span>))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">predict.lm</span>(mod_cat, <span class="at">newdata=</span>new_cats, <span class="at">interval=</span><span class="st">"confidence"</span>, <span class="at">level=</span>.<span class="dv">98</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        fit      lwr      upr
1  8.997894 8.584937  9.41085
2 10.709489 9.780337 11.63864</code></pre>
</div>
</div>
<p>These result match what was found in the step-by-step calculations above.</p>
</section>
<section id="on-your-own" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="on-your-own">On Your Own</h3>
<ol type="1">
<li>Consider the <code>bac</code> data frame from the <code>openintro</code> library.
<ol type="a">
<li><p>Fit and interpret a regression model predicting blood alcohol content as a linear function of beer consumption.</p></li>
<li><p>What do you estimate for the mean blood alcohol level when 1, 3, 5, or 7 beers are consumed?</p></li>
<li><p>What is the t-multiplier you would use for a 98% confidence interval for the mean blood alcohol level after 1 beer?</p></li>
<li><p>Would a 95% confidence interval for the mean blood alcohol level after 1 beer be wider, narrower, or the same width as a 98% confidence interval for blood alcohol after 4 beers? Explain.</p></li>
<li><p>Complete 98% confidence intervals for the mean blood alcohol levels after 1, 3, 5, and 7 cans of beer. Write out an interpretation for the 3-beer interval.</p></li>
</ol></li>
<li>Consider the <code>mtcars</code> data frame from the <code>datasets</code> library.
<ol type="a">
<li>Fit and interpret a linear regression model predicting mpg as a function of vehicle weight in 1,000s of lbs.</li>
<li>Complete and interpret a 95% confidence interval for the mean mpg of cars weight 2,000 lbs, 2,500 lbs, 3,000 lbs, and 3,500 lbs.</li>
<li>How wide are each of your intervals from part b? Why is the 2,000 lb interval so much wider than the 3,000 lb interval? Explain.</li>
<li>Complete and interpret a 98% confidence interval for the mean mpg of cars weight 3,000 lbs. How does this interval compare to the 3,000 lb interval from part b.</li>
</ol></li>
<li>Consider the speed and stopping distance data in the <code>cars</code> data frame.
<ol type="a">
<li>Fit and interpret a linear regression model predicting stopping distance as a function of speed.</li>
<li>Complete and interpret 90% confidence intervals for the mean stopping distance of cars traveling at 20 and 40 miles per hour.</li>
<li>How wide are each of your intervals from part b? Are you equally confident in each of them? Why or why not?</li>
</ol></li>
</ol>
</section>
</section>
<section id="prediction-intervals-for-y" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="prediction-intervals-for-y"><span class="header-section-number">3.3</span> Prediction Intervals for <span class="math inline">\(Y\)</span></h2>
<p>There is a new type of interval in regression modeling that is a little different than those you’ve learned up until now. Your intro stats class likely considered confidence intervals for a mean, a proportion, the difference between two means, or the difference between two proportions. In section 3.1 we looked at confidence intervals for intercept and slope for our regression fit. Section 3.2 was confidence intervals for the mean <span class="math inline">\(Y\)</span> at a given <span class="math inline">\(X=x_*\)</span>. What all of these have in common is that the interval is all about the estimate of an unknown population parameter.</p>
<p>There exists a true population mean, and you’re using your sample data to create an interval likely to capture that population parameter because measuring the entire population to calculate it directly is not feasible. Just as there exists a true slope for the relationship between X and Y for the entire population - you can’t measure the full population so you use your sample to develop an interval likely to include the population slope parameter.</p>
<p>This new type of interval, a <strong><em>prediction interval</em></strong>, isn’t about estimating an unknown population parameter. The goal with a prediction interval is to predict the next Y observation at a set <span class="math inline">\(X=x_*\)</span>. As such, prediction intervals are quite a bit wider than the corresponding confidence interval at <span class="math inline">\(X=x∗\)</span> because single observations have quite a bit more variability than means. How much more variability? Well… look back at Figure 1. What measure do we have that describes the variability of individual points around the fitted regression line? The <span class="math inline">\(S_R\)</span> term. That’s why while the standard error of <span class="math inline">\(\bar{Y}\)</span> at a given X looks like this:</p>
<p><span class="math display">\[
SE_{\bar{Y}|x_*}=S_R\sqrt{\frac{1}{n}+\frac{(x_*-\bar{x})^2}{\sum{(x_i-\bar{x})^2}}}
\]</span></p>
<p>The standard error of the next Y at a given X takes on this form:</p>
<p><span class="math display">\[
SE_{y|x_*}=S_R\sqrt{1+ \frac{1}{n}+\frac{(x_*-\bar{x})^2}{\sum{(x_i-\bar{x})^2}}}
\]</span></p>
<p>The two are nearly identical, but with the addition of a simple <span class="math inline">\(1+\)</span> we’ve added in the <span class="math inline">\(S_R\)</span> one more time to account for the variability of individual points.</p>
<p>The general form of your prediction interval is exactly as with the confidence interval: <span class="math display">\[
point\space estimate \pm multiplier\times standard \space error
\]</span></p>
<p>so if we want a 90% prediction interval for the heart weight of a cat with a body weight of 2.3, that is achieved through</p>
<p><span class="math display">\[
E(Y|(X=2.3))\pm t_{\frac{0.1}{2}, 48}\times SE_{(y|X=2.3)}
\]</span></p>
<p><span class="math display">\[
\hat{β_0}+(\hat{β_1}\times2.3)\pm 1.6772 \times 1.2007\sqrt {1+\frac{1}{50}+\frac{(2.3-2.34)^2}{3.76}}
\]</span></p>
<p><span class="math display">\[
8.9979\pm1.6772\times1.2129
\]</span></p>
<p><span class="math display">\[
(6.9636, 11.0322)
\]</span></p>
<p>Note that little <span class="math inline">\(1+\)</span> addition has a big impact. Even though this is a 90% level interval, it is much much wider than the 98% confidence interval calculated in section 3.2 for the same <span class="math inline">\(X=2.3\)</span>. That’s because while that one was about <span class="math inline">\(\bar{Y}\)</span> at <span class="math inline">\(X=2.3\)</span>, this is about a single observation. So we can now say we are 90% confident the interval ranging from 6.9636 to 11.0322 grams includes the heart weight of Fluffy, a cat with a body weight of 2.3lbs.</p>
<section id="in-r-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="in-r-1">In R</h3>
<p>For prediction intervals you’re using the <code>predict.lm</code> function again only now specifying <code>interval="prediction"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mod_cat<span class="ot">&lt;-</span><span class="fu">lm</span>(Hwt<span class="sc">~</span>Bwt, <span class="at">data=</span>cats[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>,])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>new_cats<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">Bwt=</span><span class="fu">c</span>(<span class="fl">2.3</span>, <span class="fl">2.9</span>))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">predict.lm</span>(mod_cat, <span class="at">newdata=</span>new_cats, <span class="at">interval=</span><span class="st">"prediction"</span>, <span class="at">level=</span>.<span class="dv">9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        fit      lwr      upr
1  8.997894 6.963668 11.03212
2 10.709489 8.594171 12.82481</code></pre>
</div>
</div>
</section>
<section id="on-your-own-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="on-your-own-1">On Your Own</h3>
<ol type="1">
<li><p>Consider the <code>bac</code> data frame from the <code>openintro</code> library.</p>
<ol type="a">
<li>Fit and interpret a regression model blood alcohol content as a linear function of the number of cans of beer consumed.</li>
<li>What do you estimate for the blood alcohol content when 2, 4, 6, or 8 beers are consumed?</li>
<li>What is the t-multiplier you would use for a 90% prediction interval for blood alcohol when 4 beers are consumed?</li>
<li>Complete 90% confidence intervals for blood alcohol level with 2, 4, 6, or 8 beers are consumed. Write out an interpretation for the 4-beer interval.</li>
<li>Would a 98% confidence interval for blood alcohol content when 2 beers are consumed be wider, narrower, or the same width as a 98% confidence interval for when 4 beers are consumed? Explain.</li>
</ol></li>
<li><p>Consider the <code>mtcars</code> data frame from the <code>datasets</code> library.</p>
<ol type="a">
<li>Fit and interpret a linear regression model predicting mpg as a function of vehicle weight in 1,000s of lbs.</li>
<li>Complete and interpret a 95% prediction interval for the mpg of three new cars coming out soon with weights of 2,200 lbs, 2,700 lbs, and 3,300 lbs.</li>
<li>How wide are each of your intervals from part b? Why is the 2,200 lb interval so much wider than the 3,300 lb interval? Explain.</li>
<li>Complete and interpret a 95% confidence interval for the mean mpg of cars weighing 3,300 lbs. How does this interval compare to the 3,300 lb interval from part b? Explain the difference.</li>
</ol></li>
<li><p>Consider the speed and stopping distance data in the <code>cars</code> data frame.</p>
<ol type="a">
<li>Fit and interpret a linear regression model predicting stopping distance as a function of speed.</li>
<li>Complete and interpret 90% prediction intervals for the stopping distance of cars traveling at 15, 25, 35, and 45 miles per hour.</li>
<li>How wide are each of your intervals from part b? How would the width of an interval for a car traveling at 10mph compare to the widths seen in b?</li>
<li>Are you equally confident in each of your intervals from part b? Why or why not?</li>
</ol></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Chapter2.html" class="pagination-link" aria-label="Add a Line">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Add a Line</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Chapter4.html" class="pagination-link" aria-label="Assumptions Were Made">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Assumptions Were Made</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>